import type { SiteContent } from './types';
import { business, canShow } from '../config/business';

const b = business;

export const en: SiteContent = {
  locale: 'en',
  htmlLang: 'en',
  seo: {
    title: 'Hearing Aid Center in Keçiören, Ankara | Ayaz Hearing Center',
    description:
      'Hearing aid selection, personalised fitting, ear moulds, batteries and servicing in Keçiören, Ankara. Learn about every device type and request an appointment.',
    ogAlt: 'Ayaz Hearing Center — Keçiören, Ankara',
  },
  nav: [
    { href: '#cihazlar', label: 'Devices' },
    { href: '#hizmetler', label: 'Services' },
    { href: '#merkezimiz', label: 'Our Center' },
    { href: '#yorumlar', label: 'Reviews' },
    { href: '#iletisim', label: 'Contact' },
  ],
  navCta: 'Request an Appointment',
  langSwitch: { label: 'TR', href: '/', hreflang: 'tr' },

  hero: {
    eyebrow: 'Ankara · Keçiören',
    h1: 'Hearing solutions that suit you, in Keçiören.',
    sub: 'We are with you through device selection, personalised fitting and regular servicing. Together, we compare behind-the-ear and in-canal options based on your hearing needs and everyday life.',
    ctaPrimary: 'Request an Appointment',
    ctaSecondary: 'Explore Devices',
    trust: [
      ...(canShow(b.claims.freeHearingTest) ? ['Free hearing test'] : ['Hearing assessment']),
      'Custom ear moulds',
      ...(canShow(b.claims.sgkContracted) ? ['SGK-contracted center'] : []),
      'Batteries, filters and servicing',
    ],
    deviceCaption: 'Representative RIC (receiver-in-canal) hearing aid',
  },

  explorer: {
    eyebrow: 'Take a closer look',
    h2: 'Explore a hearing aid, part by part.',
    lead: 'Rotate the model, zoom in and explore its main components. Learn what each part does; at our center you can hold and try real devices.',
    representativeNote: 'Illustrative RIC model. Parts are separated for explanation; do not dismantle your device. Designs vary by model.',
    controls: {
      rotate: 'Rotate',
      zoom: 'Zoom',
      reset: 'Reset',
      explode: 'Take apart',
      assemble: 'Assemble',
      autoRotate: 'Auto-rotate',
      explodeLabel: 'Separation level',
    },
    hotspots: [
      { id: 'mics', title: 'Microphones', text: 'Pick up sound from the surroundings. Most models have two microphones, so the device can tell which direction speech is coming from.' },
      { id: 'body', title: 'Housing and processor', text: 'The slim housing sits behind the ear; the processor inside analyses sound, reduces noise and brings speech forward.' },
      { id: 'button', title: 'Control button', text: 'Used to change the volume or programme. Many models can also be controlled from a phone app.' },
      { id: 'wire', title: 'Thin receiver wire', text: 'The almost invisible link running from the housing into the ear canal. Its length is chosen to match your ear.' },
      { id: 'receiver', title: 'Receiver (loudspeaker)', text: 'Sits inside the ear canal and delivers the processed sound to the ear. Its power level is chosen according to the hearing loss.' },
      { id: 'dome', title: 'Dome or ear mould', text: 'The soft tip that holds the receiver in the ear. Either a standard dome or a custom-made ear mould can be used.' },
      { id: 'power', title: 'Charging contacts', text: 'These contacts connect the illustrated model to its charger. Other models may use contactless charging or replaceable batteries.' },
    ],
    fallbackTitle: '3D view is not available on this device',
    fallbackText: 'The 3D model could not load, or your browser does not support WebGL2. You can read the part descriptions below and examine the devices at our center.',
    keyboardHint: 'Keyboard: arrow keys to rotate, + / − to zoom, R to reset, E to separate parts. On touchscreens, swipe horizontally to rotate.',
    loading: 'Preparing 3D model…',
    cta: 'Try the devices in person',
  },

  devices: {
    eyebrow: 'Types of hearing aid',
    h2: 'Behind the ear or in the ear? Explore your options.',
    lead: 'Hearing aids are classified by where they sit. Being rechargeable or having Bluetooth are separate features whose availability depends on the model. The comparison below is a general guide; the right choice depends on your hearing assessment, ear anatomy and everyday needs.',
    tableHeaders: {
      visibility: 'Visibility',
      power: 'Power range',
      rechargeable: 'Rechargeable option',
      wireless: 'Wireless connectivity',
      handling: 'Ease of handling',
      care: 'Maintenance',
      suits: 'Typically suits',
    },
    types: [
      {
        id: 'bte',
        code: 'BTE',
        name: 'Behind-the-ear',
        short: 'Behind-the-Ear',
        description: 'All the electronics sit in a housing behind the ear; sound travels through a tube and a suitable mould or tip. Different power levels and controls are available.',
        suits: 'A wide range from mild to profound loss; people who want larger buttons and batteries; a frequent choice for children.',
        visibility: { level: 2, label: 'Visible' },
        power: 'Mild → profound',
        rechargeable: 'Common',
        wireless: 'Common',
        handling: 'Very easy',
        care: 'Low–moderate (tube and mould cleaning)',
      },
      {
        id: 'ric',
        code: 'RIC / RITE',
        name: 'Receiver-in-canal',
        short: 'Receiver-in-Canal',
        description: 'A small housing sits behind the ear, while the receiver (loudspeaker) sits inside the ear canal on a thin wire. Its compact housing and different receiver options allow it to suit a range of needs.',
        suits: 'Mild to severe loss; adults who want a sleek, discreet device. Because the receiver power can be changed, it can be adapted if your hearing changes.',
        visibility: { level: 4, label: 'Discreet' },
        power: 'Mild → severe',
        rechargeable: 'Very common',
        wireless: 'Very common',
        handling: 'Easy',
        care: 'Moderate (receiver filter and dome care)',
      },
      {
        id: 'ite',
        code: 'ITE',
        name: 'In-the-ear',
        short: 'In-the-Ear',
        description: 'A shell made from an impression of your ear fills the inner part of the outer ear. Full-shell and half-shell options are available; nothing sits behind the ear.',
        suits: 'Mild to severe loss; people who wear glasses or masks, or who do not want anything behind the ear; those looking for an in-the-ear model that is easy to hold and has a larger button.',
        visibility: { level: 3, label: 'Moderate' },
        power: 'Mild → severe',
        rechargeable: 'Many models',
        wireless: 'Common',
        handling: 'Easy',
        care: 'Moderate–high (earwax and moisture)',
      },
      {
        id: 'itc',
        code: 'ITC',
        name: 'In-the-canal',
        short: 'In-the-Canal',
        description: 'Smaller than an ITE; it sits at the entrance of the ear canal and only a small faceplate is visible from outside. Made with a custom shell.',
        suits: 'Mild to moderately severe loss; people who want a discreet model that can still be handled and inserted by hand.',
        visibility: { level: 4, label: 'Discreet' },
        power: 'Mild → moderately severe',
        rechargeable: 'Limited',
        wireless: 'Some models',
        handling: 'Moderate',
        care: 'High (earwax and moisture)',
      },
      {
        id: 'cic',
        code: 'CIC',
        name: 'Completely-in-canal',
        short: 'Completely-in-Canal',
        description: 'Sits deep in the ear canal; visibility depends on the ear anatomy and model. Because of its small size, battery life and the feature set are more limited.',
        suits: 'Mild to moderate loss; people who prioritise discretion and are comfortable handling small parts.',
        visibility: { level: 5, label: 'Nearly invisible' },
        power: 'Mild → moderately severe (depends on canal size)',
        rechargeable: 'Rare',
        wireless: 'Limited',
        handling: 'Difficult (small parts)',
        care: 'High',
      },
      {
        id: 'iic',
        code: 'IIC',
        name: 'Invisible-in-canal',
        short: 'Invisible-in-Canal',
        description: 'A small design fitted deep in the ear canal. Visibility and fitting depth depend on the ear anatomy and model; it may not suit every ear.',
        suits: 'Mild to moderate loss; people with a suitable ear canal who want a very discreet solution.',
        visibility: { level: 5, label: 'Very discreet' },
        power: 'Mild → moderate',
        rechargeable: 'Rare',
        wireless: 'Very limited',
        handling: 'Difficult (small parts)',
        care: 'High',
        note: 'The ear canal must be of a suitable size and shape.',
      },
    ],
    systems: {
      title: 'System options independent of form factor',
      items: [
        {
          name: 'CROS / BiCROS',
          text: 'For single-sided hearing loss, a microphone on the non-hearing side sends sound wirelessly to the device in the other ear. BiCROS is used when the better ear also has some loss. It is a system feature rather than a separate device type.',
        },
        {
          name: 'Power / Super Power',
          text: 'Models that deliver high output for severe and profound losses, usually in a behind-the-ear (BTE) housing. Worn with a custom ear mould.',
        },
        {
          name: 'Options for children',
          text: 'For children, durable behind-the-ear models are preferred: the mould can be remade as the ear grows, and they work with classroom systems. Assessment and follow-up are carried out as part of the paediatric audiology process.',
        },
      ],
    },
    disclaimer: 'This table is based on the manufacturers\' general classifications. Not every model works with every phone, not every ear suits every type, and results vary from person to person. A definitive recommendation is given after a hearing assessment.',
    askCta: 'Ask about this type',
    sourcesNote: 'A general comparison. We check power, connectivity and charging options against the specifications of the chosen model.',
  },

  brands: {
    eyebrow: 'Brands and technologies',
    h2: 'We know the industry\'s leading brands well.',
    lead: 'Worldwide, hearing aid manufacturing is concentrated in a handful of large groups. Before choosing a brand, we clarify the device type, the power you need and what you expect in daily use; then we compare the options that suit you impartially.',
    featured: [
      { name: 'Phonak', group: 'Sonova', text: 'A brand of the Swiss Sonova group. Known for platforms focused on speech understanding in noise and a broad connectivity ecosystem.' },
      { name: 'Oticon', group: 'Demant', text: 'A brand of the Danish Demant group. Recognised for its "BrainHearing" approach, which aims to let the brain process sound naturally.' },
      { name: 'Widex', group: 'WS Audiology', text: 'Danish in origin; known for its natural, pure sound character, particularly its performance with music and in quiet settings.' },
      { name: 'Bernafon', group: 'Demant', text: 'A Swiss-origin brand within the Demant group. Offers a hybrid sound-processing approach that balances speech understanding with listening comfort.' },
      { name: 'Signia', group: 'WS Audiology', text: 'German in origin; formerly known as Siemens hearing aids. Stands out for speech-focused processing and elegant designs.' },
      { name: 'ReSound', group: 'GN', text: 'A brand of the Danish GN group. Offers wireless audio streaming from compatible phones to hearing aids.' },
    ],
    groupsTitle: 'Which group does each brand belong to?',
    groups: [
      { group: 'Sonova', brands: ['Phonak', 'Unitron'], note: 'Switzerland' },
      { group: 'Demant', brands: ['Oticon', 'Bernafon', 'Philips Hearing Solutions'], note: 'Denmark' },
      { group: 'WS Audiology', brands: ['Widex', 'Signia'], note: 'Denmark / Germany' },
      { group: 'GN', brands: ['ReSound', 'Beltone'], note: 'Denmark' },
      { group: 'Starkey', brands: ['Starkey'], note: 'USA, independent' },
    ],
    disclaimer: 'This section is for information only; brand names are registered trademarks of their respective companies. Please contact us for details of which brands we fit, stock and prices.',
    techTitle: 'Current technologies: what do they do?',
    tech: [
      { name: 'Speech processing in noise', text: 'The device continuously analyses the surroundings, bringing speech forward and suppressing background noise. Some platforms use AI-supported processing; results depend on the environment and model.' },
      { name: 'Rechargeable battery', text: 'Placed in the charger overnight; reduces the need to replace disposable batteries. A real convenience for anyone who struggles to handle small parts.' },
      { name: 'Bluetooth and LE Audio / Auracast', text: 'Calls and music can stream from compatible phones to the device. TV streaming may require an accessory. Auracast-enabled models can receive broadcasts directly in compatible venues. Compatibility depends on the phone model.' },
      { name: 'Personalisation via app', text: 'Volume, programme and some fine adjustments are made from a phone app; some brands also offer remote adjustment.' },
      { name: 'Telecoil (T-coil)', text: 'Picks up sound directly in places fitted with an induction loop, such as mosques, halls and service counters. Available on selected models.' },
      { name: 'Tinnitus support', text: 'Many devices include sound programmes that help mask tinnitus; used under specialist guidance.' },
    ],
  },

  services: {
    eyebrow: 'Services',
    h2: 'From the first consultation to regular servicing, all in one place.',
    lead: 'We listen to your needs, explain suitable options and support you as you use your device. Fitting, care and follow-up are as important as the initial choice.',
    items: [
      {
        id: 'test',
        icon: 'ear',
        title: 'Hearing assessment',
        text: 'Through a consultation and a hearing test, we build a picture of your current hearing together. We explain the results in plain language and present the options accordingly.',
        ...(canShow(b.claims.freeHearingTest) ? { badge: 'Free' } : {}),
      },
      { id: 'secim', icon: 'sliders', title: 'Device selection and trial', text: 'We compare the suitable types according to your degree of hearing loss, ear anatomy and lifestyle, and let you try the device on site before you decide.' },
      { id: 'uygulama', icon: 'settings', title: 'Fitting and fine-tuning', text: 'The device is programmed to your audiogram. Over the first few weeks, we make gradual adjustments based on your feedback to find the most comfortable listening settings.' },
      { id: 'kalip', icon: 'mold', title: 'Custom ear moulds', text: 'We take an impression of your ear and produce a mould that fits it exactly. We check the fit, sound delivery and comfort together.' },
      {
        id: 'pil',
        icon: 'battery',
        title: 'Batteries, filters and accessories',
        text: 'We help you find suitable batteries, receiver filters, domes and cleaning products. Compatibility and availability are checked individually. We also help with chargers and connectivity accessories.',
      },
      { id: 'bakim', icon: 'wrench', title: 'Maintenance, service and follow-up', text: 'Periodic cleaning, moisture removal and checks. If a fault occurs, we diagnose it and manage the authorised service process on your behalf.' },
      ...(canShow(b.claims.sgkContracted)
        ? [{ id: 'sgk', icon: 'file', title: 'SGK process support', text: 'As an SGK-contracted center (Turkish Social Security Institution), we guide you through the medical report and prescription process and prepare the necessary documents together. Contribution amounts and conditions change with current regulations.' }]
        : []),
    ],
  },

  earMold: {
    eyebrow: 'Ear moulds',
    h2: 'A mould made for your ear: a small part that makes a big difference.',
    lead: 'The ear mould is the custom-made part that carries the device\'s sound into your ear and holds the device in place. It is used with many behind-the-ear devices and some RIC fittings, depending on power needs and ear anatomy. The right measurement and the right material directly affect comfort, sound quality and feedback control.',
    steps: [
      { title: 'Ear canal check', text: 'The ear canal is examined before the impression is taken; any wax or irritation must be dealt with first.' },
      { title: 'Taking the impression', text: 'A small protective block is placed in the canal, then soft silicone impression material is applied. It sets within a few minutes. A trained professional carries out the procedure; tell them immediately if you feel discomfort.' },
      { title: 'Manufacture', text: 'The impression is turned into a mould using a material chosen according to the device type, the power required and the intended use.' },
      { title: 'Fit check and handover', text: 'The mould is tried in the ear and fine adjustments are made if needed. Insertion, removal and cleaning are demonstrated hands-on.' },
    ],
    types: [
      { name: 'Hard acrylic mould', text: 'Durable and easy to clean; practical to insert and remove. Holds its shape over long-term use.' },
      { name: 'Soft silicone mould', text: 'More flexible, with a better seal; preferred for power devices to reduce feedback. Widely used for children.' },
      { name: 'Skeleton / half-shell mould', text: 'Lighter, more open options that cover only part of the outer ear. Used for mild to moderate losses.' },
      { name: 'Standard dome', text: 'Ready-made silicone tips used with receiver-in-canal (RIC) devices. Open and closed options are available; the size and type depend on the fitting.' },
    ],
    care: [
      'Clean the device and mould with a soft, dry cloth as instructed by the manufacturer. Never immerse a receiver or electronic component in water.',
      'Use the recommended washing method only for detached BTE tube moulds without electronics, and dry them fully before reconnecting. Ask us to demonstrate care for your model.',
      'Ear shape changes over time; the mould may need replacing when it loosens or whistling begins.',
    ],
    distinction: 'Hearing aid moulds, swimmers\' plugs and noise-protection plugs are different products. If you need custom protective plugs, we can advise you separately.',
    cta: 'Book an ear mould appointment',
  },

  process: {
    eyebrow: 'How we work',
    h2: 'Four steps from first consultation to regular follow-up.',
    lead: 'We plan the process around your needs, explain each step and follow up on your experience.',
    steps: [
      { title: 'Consultation', text: 'We listen to your expectations, your everyday environments and any experience you have with a current device. You can book by phone or WhatsApp.' },
      { title: 'Assessment and options', text: 'After a hearing test and ear check, we compare the suitable device types and offer a trial.' },
      { title: 'Fitting and personalisation', text: 'The chosen device is adjusted to your audiogram; an ear mould is made if needed. Use and cleaning are demonstrated hands-on.' },
      { title: 'Check-ups and servicing', text: 'Fine-tuning appointments in the first few weeks, followed by regular checks and servicing. You can reach us by phone or WhatsApp with your questions.' },
    ],
    note: 'A hearing aid supports hearing; it does not replace medical assessment of the cause of hearing loss. Results vary depending on the person, the type of loss and how regularly the device is used.',
  },

  center: {
    eyebrow: 'Our center',
    h2: 'An easy-to-reach center on Ayvalı Caddesi, Keçiören.',
    lead: 'With a spacious waiting area and a separate consultation room, the whole process, from hearing assessment to device adjustment, is completed at the same center.',
    facts: [
      { label: 'Address', value: b.address.line },
      { label: 'Phone', value: b.phone.display },
      ...(canShow(b.hours) ? [{ label: 'Opening hours', value: 'Monday–Saturday 09:00–18:00' }] : []),
    ],
    teamTitle: 'Our specialist team',
    teamText: 'We listen to your needs at the first consultation and plan fitting and follow-up appointments together.',
    galleryLabel: 'Photos of the center',
    photos: [
      { key: 'ofis-6', alt: 'Ayaz Hearing Aids shopfront on Ayvalı Caddesi, Keçiören', caption: 'Our center on Ayvalı Caddesi' },
      { key: 'ofis-1', alt: 'Ayaz Hearing Center consultation room and team member', caption: 'Consultation and fitting room' },
      { key: 'ofis-3', alt: 'Waiting area: armchairs, plants and a shop window facing the street', caption: 'Waiting area' },
      { key: 'ofis-5', alt: 'Consultation room: specialist\'s desk, battery stand and a hearing anatomy poster on the wall', caption: 'Consultation room' },
      { key: 'ofis-7', alt: 'View of the waiting area from the entrance', caption: 'Entrance and waiting area' },
      { key: 'ofis-8', alt: 'View of the consultation room from the doorway', caption: 'Consultation room' },
    ],
    directionsCta: 'Get directions',
  },

  reviews: {
    eyebrow: 'Google reviews',
    h2: 'What our customers say',
    lead: 'Read experiences on our Google Business Profile and share your own.',
    ratingLabel: 'Google rating',
    countLabel: (n) => `${n} reviews`,
    seeAll: 'See all reviews on Google',
    write: 'Write a review',
    attribution: 'Reviews are provided by Google.',
    loading: 'Loading reviews…',
    offline: 'Our reviews are on Google',
    offlineText: 'Use the link to see the current rating and reviews on our Google Business Profile.',
    apiNote: 'The reviews shown here are selected by Google. Read all current reviews on Google Maps.',
  },

  faq: {
    eyebrow: 'Frequently asked questions',
    h2: 'Common questions',
    lead: 'If your question is not answered here, call or message us on WhatsApp; our team will be happy to help.',
    items: [
      { q: 'How is a hearing aid chosen?', a: 'First, a hearing test and ear check are carried out. The degree and type of loss, ear canal shape, dexterity, use of glasses or masks and your everyday environments (crowds, phone, TV) are all considered together. Suitable device types and technology levels are then compared, and you decide after trying the device.' },
      { q: 'Is in-the-ear or behind-the-ear better?', a: 'There is no single "best". Behind-the-ear and receiver-in-canal models offer a wider power range, longer battery life and easier handling. In-the-ear models have the advantage of discretion but are more exposed to earwax and moisture. The decision depends on your degree of loss and ear anatomy.' },
      { q: 'Should I choose rechargeable or battery-powered?', a: 'Rechargeable models go into the charger overnight; they are practical for anyone who finds small batteries fiddly. Battery-powered models allow uninterrupted use simply by changing the battery, with no dependence on a charger. We decide together based on your lifestyle.' },
      { q: 'Will the device connect to my phone?', a: 'Most current models stream phone calls, music and video sound directly via Bluetooth. However, compatibility depends on the phone model, its operating system and the device\'s connectivity standard; we check compatibility with your phone during the consultation.' },
      { q: 'Why is an ear mould needed, and how is it made?', a: 'The mould holds the device firmly in the ear, delivers sound without leakage and reduces whistling. A small protective block is placed in the ear canal and soft silicone impression material is applied; it sets within a few minutes. A trained professional takes the impression, and the custom mould is checked for fit at handover.' },
      { q: 'What is the adjustment period like at first?', a: 'The brain relearns sounds it has not heard for a long time. In the first few days, your own voice and ambient sounds may seem different. With a gradual increase in wearing time and fine-tuning appointments in the first weeks, most users adjust noticeably within a few weeks.' },
      { q: 'How do I look after the device, and how often are filters changed?', a: 'Follow the instructions supplied with your device for cleaning, drying and storage. Filter and dome replacement intervals depend on the model and wax build-up. We demonstrate how and when to replace them.' },
      { q: 'What happens at the first appointment, and what should I bring?', a: 'A consultation, ear check and hearing test are carried out; the results are explained and the options discussed. Just bring any previous hearing test results, the device you currently use, if any, and your ID for the SGK process.' },
      { q: 'What determines the price of a hearing aid?', a: 'Price depends less on the device type than on the technology level (noise processing, connectivity, charging), the number of channels and additional services. After the assessment, we give clear pricing for different levels suited to your needs.' },
      ...(canShow(b.claims.sgkContracted)
        ? [{ q: 'How much does SGK pay towards a hearing aid, and how does the process work?', a: 'SGK (the Turkish Social Security Institution) contributes a set amount, subject to a medical board report and a prescription; the amounts and conditions are updated through the Health Implementation Communiqué (SUT). As an SGK-contracted center, we guide you through the paperwork and share the current conditions at your consultation.' }]
        : []),
    ],
  },

  contact: {
    eyebrow: 'Contact and appointments',
    h2: 'Get in touch for a consultation.',
    lead: 'Call or WhatsApp us right away, or leave the short form and we will call you. An appointment request is confirmed once our team calls you to agree a time.',
    form: {
      title: 'Appointment request',
      name: 'Full name',
      phone: 'Phone',
      time: 'When should we call you?',
      timeOptions: ['No preference', 'Morning (09:00–12:00)', 'Afternoon (12:00–15:00)', 'Late afternoon (15:00–18:00)'],
      note: 'We do not ask for health information, reports or audiograms; we go through these together at your consultation.',
      consent: 'I have read the privacy notice on the processing of my contact details for appointment purposes.',
      consentLink: 'Privacy notice',
      submit: 'Send Appointment Request',
      submitWhatsapp: 'Send via WhatsApp',
      sending: 'Sending…',
      successTitle: 'Request received',
      successText: 'Our team will contact you to arrange an appointment, taking your preferred time into account.',
      errorTitle: 'Could not send',
      errorText: 'Something went wrong. Please contact us by phone or WhatsApp.',
      fallbackNotice: 'The form turns your request into a ready-made WhatsApp message; just confirm it in WhatsApp to send.',
      validation: {
        name: 'Please enter your full name.',
        phone: 'Please enter a valid phone number (e.g. 05xx xxx xx xx).',
        consent: 'Please confirm the privacy notice to continue.',
        time: 'Please choose a time slot.',
      },
    },
    info: {
      address: 'Address',
      phone: 'Phone',
      whatsapp: 'WhatsApp',
      email: 'Email',
      hours: 'Opening hours',
      hoursValue: 'Monday–Saturday 09:00–18:00',
      closed: 'Closed on Sundays',
      directions: 'Directions',
      loadMap: 'Load map',
      mapNote: 'The map is provided by Google; once loaded, Google\'s cookie policy applies.',
    },
  },

  footer: {
    legal: b.legalNameEn,
    privacy: 'Privacy and data protection (KVKK)',
    cookies: 'Cookie preferences',
    rights: 'All rights reserved.',
    quick: 'Quick links',
    contact: 'Contact',
    disclaimer: 'The information on this site is for general information purposes only and is not a substitute for medical diagnosis or treatment. Brand names are registered trademarks of their respective companies.',
  },

  consent: {
    title: 'Cookie preferences',
    text: 'Our site runs on essential cookies. Optional cookies used for visit statistics and ad measurement are only loaded if you give permission.',
    acceptAll: 'Accept all',
    rejectAll: 'Essential only',
    manage: 'Manage preferences',
    save: 'Save selection',
    categories: [
      { key: 'necessary', label: 'Essential', text: 'Required for the site to work and to remember your preferences. Cannot be switched off.', locked: true },
      { key: 'analytics', label: 'Analytics', text: 'Helps us understand how the page is used (Google Analytics). Usage and device information may be processed; names and phone numbers entered in the form are not sent to analytics.' },
      { key: 'marketing', label: 'Marketing', text: 'Used to measure the effectiveness of advertising campaigns (Google Ads, Meta). Only enabled measurement services run, with your permission.' },
    ],
    reopen: 'Cookie preferences',
    policyLink: 'Cookie policy',
  },

  mobileBar: { call: 'Call', whatsapp: 'WhatsApp', directions: 'Directions' },

  common: {
    skip: 'Skip to content',
    menu: 'Menu',
    close: 'Close',
    back: 'Back',
    next: 'Next',
    prev: 'Previous',
    learnMore: 'Learn more',
    new: 'New',
  },
};
