import type { SiteContent } from './types';
import { business, canShow } from '../config/business';

const b = business;

export const en: SiteContent = {
  locale: 'en',
  htmlLang: 'en',
  seo: {
    title: 'Hearing Aid Center in Keçiören, Ankara | Ayaz Hearing Center',
    description:
      'Hearing aid selection, personalised fitting, ear moulds, batteries and servicing in Keçiören, Ankara. Learn about every device type and request an appointment.',
    ogAlt: 'Ayaz Hearing Center — Keçiören, Ankara',
  },
  nav: [
    { href: '#cihazlar', label: 'Devices' },
    { href: '#hizmetler', label: 'Services' },
    { href: '#merkezimiz', label: 'Our Center' },
    { href: '#yorumlar', label: 'Reviews' },
    { href: '#iletisim', label: 'Contact' },
  ],
  navCta: 'Request an Appointment',
  langSwitch: { label: 'TR', href: '/', hreflang: 'tr' },

  hero: {
    eyebrow: 'Ankara · Keçiören',
    h1: 'Hearing solutions that suit you, in Keçiören.',
    sub: 'We are with you through device selection, personalised fitting and regular servicing. Together, we compare behind-the-ear and in-canal options based on your hearing needs and everyday life.',
    ctaPrimary: 'Request an Appointment',
    ctaSecondary: 'Explore Devices',
    trust: [
      ...(canShow(b.claims.freeHearingTest) ? ['Free hearing test'] : ['Hearing assessment']),
      'Custom ear moulds',
      ...(canShow(b.claims.sgkContracted) ? ['SGK-contracted center'] : []),
      'Batteries, filters and servicing',
    ],
    deviceCaption: 'Representative RIC (receiver-in-canal) hearing aid with a size 312 battery',
  },

  explorer: {
    eyebrow: 'Take a closer look',
    h2: 'Get to know a hearing aid up close.',
    lead: 'Rotate and zoom the three main device types, open the battery door and examine each component separately. Learn what every part does; at our center you can hold and try real devices.',
    representativeNote: 'Representative models. Taking parts apart is for explanation only; do not disassemble your device. Designs vary by brand and model.',
    controls: {
      rotate: 'Rotate',
      zoom: 'Zoom',
      reset: 'Reset view',
      explode: 'Take apart',
      autoRotate: 'Auto-rotate',
      explodeLabel: 'Separation level',
      door: 'Battery door',
      modelLabel: 'Device type',
    },
    models: [
      {
        id: 'ric',
        label: 'RIC',
        sub: 'Receiver-in-canal · size 312 battery',
        caption: 'Representative RIC (receiver-in-canal) hearing aid with a size 312 battery',
        hotspots: [
          { id: 'mics', title: 'Microphones', text: 'Pick up sound from the environment. Most models have two microphones so the device can tell which direction speech comes from.' },
          { id: 'body', title: 'Body and processor', text: 'The slim body that sits behind the ear; the processor inside analyses sound, reduces noise and brings speech forward.' },
          { id: 'button', title: 'Control button', text: 'Used to change the volume or programme. Many models can also be controlled from a phone app.' },
          { id: 'wire', title: 'Thin receiver wire', text: 'The nearly invisible link from the body to the ear canal. Its length is chosen to fit your ear.' },
          { id: 'receiver', title: 'Receiver (speaker)', text: 'Sits inside the ear canal and delivers the processed sound. Its power level is chosen according to the hearing loss.' },
          { id: 'dome', title: 'Dome or earmould', text: 'The soft tip that holds the receiver in the ear. A standard dome or a custom-made earmould can be used.' },
          { id: 'battery-door', title: 'Battery door', text: 'The drawer-style door at the bottom of the body. Pulled with a fingernail, it swings forward on its pin and brings the battery out of its compartment; closing it swings the battery back in. Leaving it slightly open switches the device off and saves the battery.' },
          { id: 'battery', title: 'Battery (size 312, brown)', text: 'A zinc-air button cell. It starts working once the tab is removed; how long it lasts depends on the device and daily use.' },
        ],
      },
      {
        id: 'bte',
        label: 'BTE',
        sub: 'Behind-the-ear · size 13 battery',
        caption: 'Representative BTE (behind-the-ear) hearing aid with a size 13 battery and earmould',
        hotspots: [
          { id: 'mics', title: 'Microphones', text: 'Two microphone ports on top of the body pick up sound and tell its direction.' },
          { id: 'body', title: 'Body and processor', text: 'The larger body allows more amplification and longer battery life; it is also used for severe hearing loss.' },
          { id: 'button', title: 'Programme and volume control', text: 'Large, easy-to-feel controls for changing programmes and adjusting volume.' },
          { id: 'hook', title: 'Ear hook', text: 'The rigid, clear curved piece screwed onto the top of the body; it holds the device over the ear and carries sound into the tube.' },
          { id: 'tube', title: 'Tube', text: 'The clear sound tube that slips over the end of the hook and fits into the earmould. It hardens over time and is replaced at regular intervals.' },
          { id: 'earmold', title: 'Earmould', text: 'Made from an impression of your ear, it fits snugly. It carries sound into the canal and reduces feedback; hard acrylic or soft silicone.' },
          { id: 'battery-door', title: 'Battery door', text: 'The drawer-style door at the bottom of the body; the battery comes out with it when opened. Its larger size makes battery changes easy.' },
          { id: 'battery', title: 'Battery (size 13, orange)', text: 'A larger zinc-air cell that usually lasts longer.' },
        ],
      },
      {
        id: 'cic',
        label: 'CIC',
        sub: 'Completely-in-canal · size 10 battery',
        caption: 'Representative CIC (completely-in-canal) hearing aid with a size 10 battery',
        hotspots: [
          { id: 'shell', title: 'Shell', text: 'A custom shell made from an impression of your ear canal. It sits deep in the canal and is barely visible from outside.' },
          { id: 'faceplate', title: 'Faceplate', text: 'The surface facing the canal entrance; it carries the microphone, the battery door and the removal string.' },
          { id: 'mic', title: 'Microphone port', text: 'The small opening on the faceplate. The natural shape of the outer ear helps preserve the direction of sound.' },
          { id: 'battery-door', title: 'Battery door', text: 'The tiny hinged door on the faceplate; opened with a fingernail, it brings the battery out with it. Changing it may be fiddly for people who find small parts hard to handle.' },
          { id: 'battery', title: 'Battery (size 10, yellow)', text: 'The smallest zinc-air cell. Because of its size it lasts less than the batteries of other types.' },
          { id: 'vent', title: 'Vent', text: 'A thin channel along the shell that reduces the feeling of pressure and the boomy sound of your own voice.' },
          { id: 'pull-string', title: 'Removal string', text: 'A thin nylon string that lets you take the device out of the ear easily.' },
          { id: 'receiver-outlet', title: 'Sound outlet and wax guard', text: 'The sound outlet at the tip facing the canal, protected by a replaceable wax filter.' },
        ],
      },
    ],
    fallbackTitle: '3D view is not available on this device',
    fallbackText: 'Your browser could not start the WebGL2 connection needed for 3D viewing in this session. You can read the part descriptions below and examine the devices at our center.',
    loadErrorTitle: 'The 3D model could not be loaded',
    loadErrorText: 'Something went wrong while loading. Reload the page to try again; device images and part descriptions are still available.',
    reloadLabel: 'Reload page',
    keyboardHint: 'Keyboard: arrow keys rotate, + / − zoom, R resets, E takes the parts apart, B opens the battery door. On touch screens, drag horizontally to rotate.',
    loading: 'Preparing the 3D model…',
    cta: 'Try the devices in person',
  },

  devices: {
    eyebrow: 'Types of hearing aid',
    h2: 'Behind the ear or in the ear? Explore your options.',
    lead: 'Hearing aids are classified by where they sit. Being rechargeable or having Bluetooth are separate features whose availability depends on the model. The comparison below is a general guide; the right choice depends on your hearing assessment, ear anatomy and everyday needs.',
    tableHeaders: {
      visibility: 'Visibility',
      power: 'Power range',
      rechargeable: 'Rechargeable option',
      wireless: 'Wireless connectivity',
      handling: 'Ease of handling',
      care: 'Maintenance',
      suits: 'Typically suits',
    },
    types: [
      {
        id: 'bte',
        code: 'BTE',
        name: 'Behind-the-ear',
        short: 'Behind-the-Ear',
        description: 'All the electronics sit in a housing behind the ear; sound travels through a tube and a suitable mould or tip. Different power levels and controls are available.',
        suits: 'A wide range from mild to profound loss; people who want larger buttons and batteries; a frequent choice for children.',
        visibility: { level: 5, label: 'Visible' },
        power: 'Mild → profound',
        rechargeable: 'Common',
        wireless: 'Common',
        handling: 'Very easy',
        care: 'Low–moderate (tube and mould cleaning)',
      },
      {
        id: 'ric',
        code: 'RIC / RITE',
        name: 'Receiver-in-canal',
        short: 'Receiver-in-Canal',
        description: 'A small housing sits behind the ear, while the receiver (loudspeaker) sits inside the ear canal on a thin wire. Its compact housing and different receiver options allow it to suit a range of needs.',
        suits: 'Mild to profound loss (with a power receiver); adults who want a sleek, discreet device. Because the receiver power can be changed, it can be adapted if your hearing changes.',
        visibility: { level: 3, label: 'Discreet' },
        power: 'Mild → profound (depends on receiver)',
        rechargeable: 'Very common',
        wireless: 'Very common',
        handling: 'Easy',
        care: 'Moderate (receiver filter and dome care)',
      },
      {
        id: 'ite',
        code: 'ITE',
        name: 'In-the-ear',
        short: 'In-the-Ear',
        description: 'A shell made from an impression of your ear fills the inner part of the outer ear. Full-shell and half-shell options are available; nothing sits behind the ear.',
        suits: 'Mild to severe loss; people who wear glasses or masks, or who do not want anything behind the ear; those looking for an in-the-ear model that is easy to hold and has a larger button.',
        visibility: { level: 4, label: 'Moderate' },
        power: 'Mild → severe',
        rechargeable: 'Many models',
        wireless: 'Common',
        handling: 'Easy',
        care: 'Moderate–high (earwax and moisture)',
      },
      {
        id: 'itc',
        code: 'ITC',
        name: 'In-the-canal',
        short: 'In-the-Canal',
        description: 'Smaller than an ITE; it sits at the entrance of the ear canal and only a small faceplate is visible from outside. Made with a custom shell.',
        suits: 'Mild to moderately severe loss; people who want a discreet model that can still be handled and inserted by hand.',
        visibility: { level: 3, label: 'Discreet' },
        power: 'Mild → moderately severe',
        rechargeable: 'Limited',
        wireless: 'Some models',
        handling: 'Moderate',
        care: 'High (earwax and moisture)',
      },
      {
        id: 'cic',
        code: 'CIC',
        name: 'Completely-in-canal',
        short: 'Completely-in-Canal',
        description: 'Sits deep in the ear canal; visibility depends on the ear anatomy and model. Because of its small size, battery life and the feature set are more limited.',
        suits: 'Mild to moderately severe loss (depends on canal size); people who prioritise discretion and are comfortable handling small parts.',
        visibility: { level: 2, label: 'Very discreet' },
        power: 'Mild → moderately severe (depends on canal size)',
        rechargeable: 'Rare',
        wireless: 'Limited',
        handling: 'Difficult (small parts)',
        care: 'High',
      },
      {
        id: 'iic',
        code: 'IIC',
        name: 'Invisible-in-canal',
        short: 'Invisible-in-Canal',
        description: 'A small design fitted deep in the ear canal. Visibility and fitting depth depend on the ear anatomy and model; it may not suit every ear.',
        suits: 'Mild to moderate loss; people with a suitable ear canal who want a very discreet solution.',
        visibility: { level: 1, label: 'Nearly invisible' },
        power: 'Mild → moderate',
        rechargeable: 'Rare',
        wireless: 'Very limited',
        handling: 'Difficult (small parts)',
        care: 'High',
        note: 'The ear canal must be of a suitable size and shape.',
      },
    ],
    systems: {
      title: 'Systems for specific needs',
      items: [
        { id: 'cros', name: 'CROS / BiCROS', text: 'For single-sided loss, sound from the non-hearing side is sent wirelessly to the other ear. BiCROS: when the better ear also has some loss.' },
        { id: 'power', name: 'Power / Super Power', text: 'High output for severe and profound losses; usually a behind-the-ear housing with a custom mould.' },
        { id: 'kids', name: 'For children', text: 'Durable behind-the-ear models that work with classroom systems. The mould is remade as the ear grows.' },
      ],
    },
    disclaimer: 'This table is based on the manufacturers\' general classifications. Not every model works with every phone, not every ear suits every type, and results vary from person to person. A definitive recommendation is given after a hearing assessment.',
    askCta: 'Ask about this type',
    figure: {
      earLabel: (name) => `Illustration: ${name} hearing aid on the ear`,
      thumbAlt: (code) => `Representative render of the ${code} hearing aid type (created from a 3D model)`,
      visibilityAria: (level, label) => `Visibility: ${level} out of 5 (${label})`,
      behindEarNote: 'Illustration. The part behind the ear is drawn semi-transparent to show where it sits.',
      inEarNote: 'Illustration. The actual look depends on the ear and the model.',
    },
    sourcesNote: 'A general comparison. We check power, connectivity and charging options against the specifications of the chosen model.',
  },

  brands: {
    eyebrow: 'Brands and technologies',
    h2: 'Major hearing aid brands and the groups they belong to.',
    lead: 'Most brands belong to a handful of large manufacturer groups. We first clarify what you need, then compare the options that suit you impartially.',
    wallTitle: 'Brands and their parent groups',
    groups: [
      { group: 'Sonova', label: 'Sonova group', brands: ['Phonak', 'Unitron'] },
      { group: 'Demant', label: 'Demant group', brands: ['Oticon', 'Bernafon', 'Philips Hearing Solutions'] },
      { group: 'WS Audiology', label: 'WS Audiology group', brands: ['Widex', 'Signia'] },
      { group: 'GN', label: 'GN group', brands: ['ReSound', 'Beltone'] },
      { group: 'Starkey', label: 'Independent manufacturer', brands: ['Starkey'] },
    ],
    disclaimer: 'For information only; brand names are registered trademarks of their owners. Please contact us about the brands we fit, stock and prices.',
    techTitle: 'Current technologies',
    tech: [
      { name: 'Speech in noise', text: 'Brings speech forward and reduces background noise.' },
      { name: 'Rechargeable battery', text: 'Charged overnight; reduces the need to change disposable batteries.' },
      { name: 'Bluetooth · Auracast', text: 'Calls and music from your phone; Auracast broadcasts in equipped venues.' },
      { name: 'Phone app', text: 'Volume and programme are adjusted from your phone.' },
      { name: 'Telecoil (T-coil)', text: 'Picks up sound directly in venues with an induction loop.' },
      { name: 'Tinnitus support', text: 'Sound programmes that help mask tinnitus; used on specialist advice.' },
    ],
    techNote: 'Features vary by brand, model and phone.',
  },

  services: {
    eyebrow: 'Services',
    h2: 'From the first consultation to regular servicing, all in one place.',
    lead: 'Fitting, care and support matter as much as choosing the device.',
    items: [
      {
        id: 'test',
        icon: 'ear',
        title: 'Hearing assessment',
        text: 'A consultation and hearing test show where you stand; we explain the results in plain language.',
        ...(canShow(b.claims.freeHearingTest) ? { badge: 'Free' } : {}),
      },
      { id: 'secim', icon: 'sliders', title: 'Device selection and trial', text: 'We compare the types that suit you and let you try the device on site before you decide.' },
      { id: 'uygulama', icon: 'settings', title: 'Fitting and fine-tuning', text: 'The device is programmed to your audiogram and adjusted gradually over the first weeks.' },
      { id: 'kalip', icon: 'mold', title: 'Custom ear moulds', text: 'From an impression of your ear, we produce a mould that fits it exactly.' },
      { id: 'pil', icon: 'battery', title: 'Batteries, filters and accessories', text: 'Together we choose the right batteries, filters, domes and cleaning products for your device.' },
      { id: 'bakim', icon: 'wrench', title: 'Maintenance, service and follow-up', text: 'Periodic cleaning and checks; if a fault occurs, we manage the authorised service process.' },
      ...(canShow(b.claims.sgkContracted)
        ? [{ id: 'sgk', icon: 'file', title: 'SGK process support', text: 'As an SGK-contracted center (Turkish Social Security Institution), we guide you through the report and prescription process; conditions follow current regulations.' }]
        : []),
    ],
  },

  earMold: {
    eyebrow: 'Ear moulds',
    h2: 'A mould made for your ear: a small part that makes a big difference.',
    lead: 'It carries the device\'s sound into your ear and holds the device in place. The right fit directly affects comfort, sound quality and feedback control.',
    steps: [
      { title: 'Ear check', text: 'The ear canal is examined with an otoscope before the impression.' },
      { title: 'Impression', text: 'A small protective block goes in, a silicone impression is taken, then the canal is checked again.' },
      { title: 'Manufacture', text: 'The impression becomes a mould in a suitable material.' },
      { title: 'Fit and handover', text: 'The mould is tried on and adjusted if needed; insertion and cleaning are shown.' },
    ],
    imageAlt: 'Representative render of a skeleton ear mould (created from a 3D model)',
    stylesTitle: 'Mould styles',
    stylesNote: 'Representative renders, shown to the same scale; names vary between labs. The right style is chosen together, based on your ear, device and hearing loss.',
    styles: [
      { id: 'full-shell', name: 'Full shell', text: 'Fills the whole concha bowl; common with high-power aids.' },
      { id: 'half-shell', name: 'Half shell', text: 'Fills the lower concha bowl; easier to insert and remove.' },
      { id: 'skeleton', name: 'Skeleton', text: 'A ring around the concha rim; open centre, good retention.' },
      { id: 'semi-skeleton', name: 'Semi-skeleton', text: 'Held by the canal and a helix arm; part of the ring is open.' },
      { id: 'canal', name: 'Canal', text: 'Sits in the canal and its entrance; the concha is left free.' },
      { id: 'canal-lock', name: 'Canal lock', text: 'A canal mould with a small lock on the lower concha rim.' },
      { id: 'cros', name: 'CROS (open)', text: 'An open mould that holds the tube or receiver without blocking the canal.' },
      { id: 'micro', name: 'Micro canal', text: 'A small mould that sits fully in the canal; often with RIC.' },
    ],
    materialsTitle: 'Material and RIC tip',
    materials: [
      { id: 'acrylic', name: 'Hard acrylic', text: 'Durable, keeps its shape, easy to clean.' },
      { id: 'silicone', name: 'Soft silicone', text: 'Flexible and comfortable; often chosen for children.' },
      { id: 'dome', name: 'Standard dome', text: 'Ready-made RIC tip: open, closed or double (power).' },
    ],
    careTitle: 'Care tips',
    care: [
      'Clean with a soft, dry cloth as the manufacturer instructs; never put a receiver or any part with electronics in water.',
      'Wash only a detached BTE tube mould with no electronics, as recommended; dry it fully before reconnecting.',
      'If the mould loosens or whistling persists, have it checked; it may need replacing.',
    ],
    distinction: 'An earmould is different from a swim plug or noise protector. We can also advise on protective plugs.',
    cta: 'Book an ear mould appointment',
  },

  process: {
    eyebrow: 'How we work',
    h2: 'Four steps from first consultation to regular follow-up.',
    lead: 'At every step we explain what we do and why.',
    steps: [
      { title: 'Consultation', text: 'We listen to your expectations and everyday environments.' },
      { title: 'Assessment', text: 'After a hearing test and ear check, we compare the options.' },
      { title: 'Fitting', text: 'The device is adjusted to your hearing and its use is shown.' },
      { title: 'Follow-up and care', text: 'Fine-tuning appointments, then regular check-ups.' },
    ],
    note: 'A hearing aid supports hearing; it does not replace medical assessment of the cause of hearing loss. Results vary from person to person.',
  },

  center: {
    eyebrow: 'Our center',
    h2: 'An easy-to-reach center on Ayvalı Caddesi, Keçiören.',
    lead: 'With a spacious waiting area and a separate consultation room, the whole process, from hearing assessment to device adjustment, is completed at the same center.',
    facts: [
      { label: 'Address', value: b.address.line },
      { label: 'Phone', value: b.phone.display },
      ...(canShow(b.hours) ? [{ label: 'Opening hours', value: 'Monday–Saturday 09:00–\u206019:00' }] : []),
    ],
    teamTitle: 'Our specialist team',
    teamText: 'We begin by listening, and together we look at your needs and your everyday life. From choosing your device and fitting it to your ears, through getting used to it, to care and regular follow-up, we are with you at every step. We are here to answer your questions and to help you use your hearing aid comfortably in daily life.',
    galleryLabel: 'Photos of the center',
    photos: [
      { key: 'ofis-6', alt: 'Ayaz Hearing Aids shopfront on Ayvalı Caddesi, Keçiören', caption: 'Our center on Ayvalı Caddesi' },
      { key: 'ofis-1', alt: 'Ayaz Hearing Center consultation room and team member', caption: 'Consultation and fitting room' },
      { key: 'ofis-3', alt: 'Waiting area: armchairs, plants and a shop window facing the street', caption: 'Waiting area' },
      { key: 'ofis-5', alt: 'Consultation room: specialist\'s desk, battery stand and a hearing anatomy poster on the wall', caption: 'Consultation room' },
      { key: 'ofis-7', alt: 'View of the waiting area from the entrance', caption: 'Entrance and waiting area' },
      { key: 'ofis-8', alt: 'View of the consultation room from the doorway', caption: 'Consultation room from the door' },
    ],
    directionsCta: 'Get directions',
  },

  reviews: {
    eyebrow: 'Google reviews',
    h2: 'What our customers say',
    lead: 'Read experiences on our Google Business Profile and share your own.',
    ratingLabel: 'Google rating',
    countLabel: (n) => `${n} reviews`,
    seeAll: 'See all reviews on Google',
    write: 'Write a review',
    attribution: 'Reviews are provided by Google.',
    loading: 'Loading reviews…',
    offline: 'Our reviews are on Google',
    offlineText: 'Use the link to see the current rating and reviews on our Google Business Profile.',
    apiNote: 'A selection of reviews from our Google Business Profile; some current reviews provided by Google are also added live. Read all reviews on Google Maps.',
    selectionNote: 'A selection of reviews from our Google Business Profile. Read all reviews on Google Maps.',
    carousel: { label: 'Customer reviews', prev: 'Previous reviews', next: 'Next reviews', pause: 'Pause auto-scroll', play: 'Start auto-scroll', slide: 'Review', googleBadge: 'Google review' },
    linkMode: {
      eyebrow: 'Google Business Profile',
      h2: 'Experiences on Google',
      lead: 'You can read what people say about our centre on our Google Business Profile, and share your own experience there.',
      seeAll: 'See reviews on Google',
      write: 'Review us on Google',
      note: 'Reviews are published on Google by users from their own accounts; we do not quote them on this site.',
    },
  },

  faq: {
    eyebrow: 'Frequently asked questions',
    h2: 'Common questions',
    lead: 'If your question is not answered here, call or message us on WhatsApp; our team will be happy to help.',
    items: [
      { q: 'How is a hearing aid chosen?', a: 'First, a hearing test and ear check are carried out. The degree and type of loss, ear canal shape, dexterity, use of glasses or masks and your everyday environments (crowds, phone, TV) are all considered together. Suitable device types and technology levels are then compared, and you decide after trying the device.' },
      { q: 'Is in-the-ear or behind-the-ear better?', a: 'There is no single "best". Behind-the-ear and receiver-in-canal models offer a wider power range, longer battery life and easier handling. Smaller in-the-ear models (ITC, CIC, IIC) have the advantage of discretion but are more exposed to earwax and moisture. The decision depends on your degree of loss and ear anatomy.' },
      { q: 'Should I choose rechargeable or battery-powered?', a: 'Rechargeable models go into the charger overnight; they are practical for anyone who finds small batteries fiddly. Battery-powered models allow uninterrupted use simply by changing the battery, with no dependence on a charger. We decide together based on your lifestyle.' },
      { q: 'Will the device connect to my phone?', a: 'Most current models stream phone calls, music and video sound directly via Bluetooth. However, compatibility depends on the phone model, its operating system and the device\'s connectivity standard; we check compatibility with your phone during the consultation.' },
      { q: 'Why is an ear mould needed, and how is it made?', a: 'A well-fitting mould holds the device firmly in the ear, delivers sound without leakage and reduces whistling. The ear canal is first examined with an otoscope; a small protective block is placed in the canal and silicone impression material is applied. It sets within a few minutes, and the canal is checked again afterwards. A trained professional takes the impression, and the custom mould is checked for fit at handover.' },
      { q: 'What is the adjustment period like at first?', a: 'The brain relearns sounds it has not heard for a long time. In the first few days, your own voice and ambient sounds may seem different. With a gradual increase in wearing time and fine-tuning appointments in the first weeks, most users adjust noticeably within a few weeks.' },
      { q: 'How do I look after the device, and how often are filters changed?', a: 'Follow the instructions supplied with your device for cleaning, drying and storage. Filter and dome replacement intervals depend on the model and wax build-up. We demonstrate how and when to replace them.' },
      { q: 'What happens at the first appointment, and what should I bring?', a: `A consultation, ear check and hearing test are carried out; the results are explained and the options discussed. ${canShow(b.claims.sgkContracted) ? 'Just bring any previous hearing test results, the device you currently use, if any, and your ID for the SGK (Turkish Social Security Institution) process.' : 'Just bring any previous hearing test results and the device you currently use, if any.'}` },
      { q: 'What determines the price of a hearing aid?', a: 'Price depends less on the device type than on the technology level (noise processing, connectivity, charging), the number of channels and additional services. After the assessment, we give clear pricing for different levels suited to your needs.' },
      ...(canShow(b.claims.sgkContracted)
        ? [{ q: 'How much does SGK pay towards a hearing aid, and how does the process work?', a: 'SGK (the Turkish Social Security Institution) contributes a set amount, subject to a medical board report and a prescription; the amounts and conditions are updated through the Health Implementation Communiqué (SUT). As an SGK-contracted center, we guide you through the paperwork and share the current conditions at your consultation.' }]
        : []),
    ],
  },

  contact: {
    eyebrow: 'Contact and appointments',
    h2: 'Get in touch for a consultation.',
    lead: 'Call or WhatsApp us right away, or leave the short form and we will call you. An appointment request is confirmed once our team calls you to agree a time.',
    form: {
      title: 'Appointment request',
      name: 'Full name',
      phone: 'Phone',
      time: 'When should we call you?',
      timeOptions: ['No preference', 'Morning (09:00–12:00)', 'Afternoon (12:00–15:00)', 'Late afternoon (15:00–19:00)'],
      note: 'We do not ask for health information, reports or audiograms; we go through these together at your consultation.',
      consent: 'I have read the privacy notice on the processing of my contact details for appointment purposes.',
      consentLink: 'Privacy notice',
      submit: 'Send Appointment Request',
      submitWhatsapp: 'Send via WhatsApp',
      sending: 'Sending…',
      successTitle: 'Request received',
      successText: 'Our team will contact you to arrange an appointment, taking your preferred time into account.',
      errorTitle: 'Could not send',
      errorText: 'Something went wrong. Please contact us by phone or WhatsApp.',
      fallbackNotice: 'The form turns your request into a ready-made WhatsApp message; just confirm it in WhatsApp to send.',
      noScript: 'The form needs JavaScript to be enabled in your browser. You can also reach us by phone or WhatsApp.',
      requiredNote: 'Required fields',
      validation: {
        name: 'Please enter your full name.',
        phone: 'Please enter a valid phone number (e.g. 05xx xxx xx xx).',
        consent: 'Please confirm the privacy notice to continue.',
        time: 'Please choose a time slot.',
      },
    },
    info: {
      address: 'Address',
      phone: 'Phone',
      whatsapp: 'WhatsApp',
      email: 'Email',
      hours: 'Opening hours',
      hoursValue: 'Monday–Saturday 09:00–\u206019:00',
      closed: 'Closed on Sundays',
      directions: 'Directions',
      loadMap: 'Load map',
      mapNote: 'The map is provided by Google and loads without waiting for consent; your IP address and the page address are sent to Google, which may use cookies. The address and phone number are also shown as text in this section.',
    },
  },

  footer: {
    legal: b.legalNameEn,
    privacy: 'Privacy and data protection (KVKK)',
    cookies: 'Cookie preferences',
    rights: 'All rights reserved.',
    quick: 'Quick links',
    contact: 'Contact',
    disclaimer: 'The information on this site is for general information purposes only and is not a substitute for medical diagnosis or treatment. Brand names are registered trademarks of their respective companies.',
  },

  consent: {
    title: 'Cookie preferences',
    noticeTitle: 'About cookies',
    textWithOptional: 'Our own site code does not use cookies. Optional measurement services ({services}) are only loaded if you give permission. The Google Maps map in the contact section, however, loads without waiting for consent; details are in the cookie policy.',
    textNoticeOnly: 'Our own site code does not use cookies, and no analytics or ad measurement service runs on this site. The Google Maps map in the contact section loads without waiting for consent; Google may use cookies. Details are in the cookie policy.',
    and: 'and',
    acceptAll: 'Accept all',
    rejectAll: 'Essential only',
    manage: 'Manage preferences',
    save: 'Save selection',
    acknowledge: 'Got it',
    categories: {
      necessary: { label: 'Essential', text: 'Required for the site to work and to remember your preferences. Cannot be switched off.' },
      analytics: { label: 'Analytics', text: 'Helps us understand how the page is used ({services}). Usage and device information may be processed; names and phone numbers entered in the form are not sent to analytics.' },
      marketing: { label: 'Marketing', text: 'Used to measure the effectiveness of advertising campaigns ({services}). Runs only with your permission.' },
    },
    reopen: 'Cookie preferences',
    policyLink: 'Cookie policy',
  },

  mobileBar: { call: 'Call', whatsapp: 'WhatsApp', directions: 'Directions' },

  common: {
    skip: 'Skip to content',
    menu: 'Menu',
    close: 'Close',
    back: 'Back',
    next: 'Next',
    prev: 'Previous',
    learnMore: 'Learn more',
    new: 'New',
  },
};
