import type { SiteContent } from './types';
import { business, canShow } from '../config/business';

const b = business;

export const tr: SiteContent = {
  locale: 'tr',
  htmlLang: 'tr',
  seo: {
    title: 'Keçiören İşitme Cihazı Merkezi | Ayaz İşitme Merkezi · Ankara',
    description:
      'Ankara Keçiören\'de işitme cihazı seçimi, kişiye özel uygulama, kulak kalıbı, pil ve bakım. Kulak arkası ve kulak içi seçenekleri inceleyin; randevu talep edin.',
    ogAlt: 'Ayaz İşitme Merkezi — Keçiören, Ankara',
  },
  nav: [
    { href: '#cihazlar', label: 'Cihazlar' },
    { href: '#hizmetler', label: 'Hizmetler' },
    { href: '#merkezimiz', label: 'Merkezimiz' },
    { href: '#yorumlar', label: 'Yorumlar' },
    { href: '#iletisim', label: 'İletişim' },
  ],
  navCta: 'Randevu Talep Et',
  langSwitch: { label: 'EN', href: '/en/', hreflang: 'en' },

  hero: {
    eyebrow: 'Ankara · Keçiören',
    h1: 'Keçiören\'de size uygun işitme çözümleri.',
    sub: 'Cihaz seçimi, kişiye özel uygulama ve düzenli bakım sürecinde yanınızdayız. Kulak arkası ve kanal içi seçenekleri, işitme ihtiyaçlarınıza ve günlük yaşamınıza göre birlikte değerlendiriyoruz.',
    ctaPrimary: 'Randevu Talep Et',
    ctaSecondary: 'Cihazları Keşfet',
    trust: [
      ...(canShow(b.claims.freeHearingTest) ? ['Ücretsiz işitme testi'] : ['İşitme değerlendirmesi']),
      'Kişiye özel kulak kalıbı',
      ...(canShow(b.claims.sgkContracted) ? ['SGK anlaşmalı merkez'] : []),
      'Pil, filtre ve bakım',
    ],
    deviceCaption: 'Temsili RIC (alıcısı kanalda) işitme cihazı',
  },

  explorer: {
    eyebrow: 'Yakından inceleyin',
    h2: 'Bir işitme cihazını yakından tanıyın.',
    lead: 'Modeli döndürün, yakınlaştırın ve temel bileşenlerini ayrı ayrı inceleyin. Her parçanın ne işe yaradığını öğrenin; merkezimizde gerçek cihazları elinize alıp deneyebilirsiniz.',
    representativeNote: 'Temsili RIC cihazı. Parçaların ayrılması anlatım amaçlıdır; cihazı kendiniz sökmeyin. Tasarım modele göre değişir.',
    controls: {
      rotate: 'Döndür',
      zoom: 'Yakınlaştır',
      reset: 'Başa dön',
      explode: 'Parçaları ayır',
      assemble: 'Birleştir',
      autoRotate: 'Otomatik döndürme',
      explodeLabel: 'Ayrışma oranı',
    },
    hotspots: [
      { id: 'mics', title: 'Mikrofonlar', text: 'Ortamdaki sesi alır. Çoğu modelde iki mikrofon bulunur; böylece cihaz konuşmanın hangi yönden geldiğini ayırt edebilir.' },
      { id: 'body', title: 'Gövde ve işlemci', text: 'Kulak arkasına oturan ince gövde; içindeki işlemci sesi analiz eder, gürültüyü azaltır ve konuşmayı öne çıkarır.' },
      { id: 'button', title: 'Kontrol düğmesi', text: 'Ses seviyesini veya programı değiştirmek için kullanılır. Birçok model telefon uygulamasıyla da kontrol edilir.' },
      { id: 'wire', title: 'İnce alıcı kablosu', text: 'Gövdeden kulak kanalına giden neredeyse görünmez bağlantı. Uzunluğu kulak yapınıza göre seçilir.' },
      { id: 'receiver', title: 'Alıcı (hoparlör)', text: 'Kulak kanalının içinde yer alır ve işlenmiş sesi kulağa iletir. Güç seviyesi işitme kaybına göre seçilir.' },
      { id: 'dome', title: 'Dome veya kulak kalıbı', text: 'Alıcıyı kulakta tutan yumuşak uç. Standart dome ya da kişiye özel üretilen kulak kalıbı kullanılabilir.' },
      { id: 'power', title: 'Şarj kontakları', text: 'Bu temsili modelde şarj ünitesiyle bağlantı kuran temas noktaları gösterilir. Diğer modellerde temassız şarj veya değiştirilebilir pil kullanılabilir.' },
    ],
    fallbackTitle: '3B görünüm bu cihazda kullanılamıyor',
    fallbackText: '3B model yüklenemedi veya tarayıcınız WebGL2 desteği sunmuyor. Parça açıklamalarını aşağıda okuyabilir, cihazları merkezimizde inceleyebilirsiniz.',
    keyboardHint: 'Klavye: ok tuşlarıyla döndürün, + / − ile yakınlaştırın, R ile başa dönün, E ile parçaları ayırın. Dokunmatik ekranda yatay sürükleyerek döndürün.',
    loading: '3B model hazırlanıyor…',
    cta: 'Cihazları yerinde deneyin',
  },

  devices: {
    eyebrow: 'İşitme cihazı türleri',
    h2: 'Kulak arkası mı, kulak içi mi? Seçenekleri tanıyın.',
    lead: 'İşitme cihazları yerleşim biçimine göre ayrılır. Şarjlı olması veya Bluetooth desteği ise ayrı birer özelliktir ve bulunabilirliği modele göre değişir. Aşağıdaki karşılaştırma genel bir rehberdir; doğru seçim işitme değerlendirmesi, kulak yapısı ve günlük ihtiyaçlarınıza göre yapılır.',
    tableHeaders: {
      visibility: 'Görünürlük',
      power: 'Güç aralığı',
      rechargeable: 'Şarjlı seçenek',
      wireless: 'Kablosuz bağlantı',
      handling: 'Kullanım kolaylığı',
      care: 'Bakım ihtiyacı',
      suits: 'Genellikle kimler için',
    },
    types: [
      {
        id: 'bte',
        code: 'BTE',
        name: 'Kulak arkası',
        short: 'Behind-the-Ear',
        description: 'Tüm elektronik parçalar kulak arkasındaki gövdede yer alır; ses bir hortum ve uygun kalıp veya uç aracılığıyla kulağa iletilir. Farklı güç seviyeleri ve kontrol seçenekleri bulunur.',
        suits: 'Hafiften çok ileri dereceye kadar geniş bir aralık; büyük düğme ve pil isteyenler; çocuklar için sık tercih edilen tür.',
        visibility: { level: 2, label: 'Görünür' },
        power: 'Hafif → çok ileri',
        rechargeable: 'Yaygın',
        wireless: 'Yaygın',
        handling: 'Çok kolay',
        care: 'Düşük–orta (hortum ve kalıp temizliği)',
      },
      {
        id: 'ric',
        code: 'RIC / RITE',
        name: 'Alıcısı kanalda',
        short: 'Receiver-in-Canal',
        description: 'Küçük gövde kulak arkasında, alıcı (hoparlör) ise ince bir kabloyla kulak kanalının içindedir. Kompakt gövdesi ve farklı alıcı seçenekleriyle birçok ihtiyaca uyarlanabilir.',
        suits: 'Hafiften ileri dereceye; şık ve az görünür bir cihaz isteyen yetişkinler. Alıcı gücü değiştirilebildiği için işitme değişirse uyarlanabilir.',
        visibility: { level: 4, label: 'Az görünür' },
        power: 'Hafif → ileri',
        rechargeable: 'Çok yaygın',
        wireless: 'Çok yaygın',
        handling: 'Kolay',
        care: 'Orta (alıcı filtresi ve dome bakımı)',
      },
      {
        id: 'ite',
        code: 'ITE',
        name: 'Kulak içi',
        short: 'In-the-Ear',
        description: 'Kulak izinizden üretilen kabuk, kulak kepçesinin iç kısmını doldurur. Tam veya yarım kabuk seçenekleri vardır; kulak arkasında hiçbir parça yoktur.',
        suits: 'Hafiften ileri dereceye; gözlük veya maske kullananlar, kulak arkasında cihaz istemeyenler; tutması kolay, düğmesi büyük bir kulak içi model arayanlar.',
        visibility: { level: 3, label: 'Orta' },
        power: 'Hafif → ileri',
        rechargeable: 'Birçok modelde',
        wireless: 'Yaygın',
        handling: 'Kolay',
        care: 'Orta–yüksek (kulak kiri ve nem)',
      },
      {
        id: 'itc',
        code: 'ITC',
        name: 'Kanal içi',
        short: 'In-the-Canal',
        description: 'ITE\'den daha küçük; kulak kanalının girişine oturur ve dışarıdan yalnızca küçük bir yüzü görünür. Kişiye özel kabukla üretilir.',
        suits: 'Hafiften orta-ileri dereceye; az görünür ama yine de elle tutulup yerleştirilebilen bir model isteyenler.',
        visibility: { level: 4, label: 'Az görünür' },
        power: 'Hafif → orta-ileri',
        rechargeable: 'Sınırlı',
        wireless: 'Bazı modellerde',
        handling: 'Orta',
        care: 'Yüksek (kulak kiri ve nem)',
      },
      {
        id: 'cic',
        code: 'CIC',
        name: 'Tamamen kanal içi',
        short: 'Completely-in-Canal',
        description: 'Kulak kanalının derininde durur; görünürlüğü kulak yapısına ve modele göre değişir. Küçük boyutu nedeniyle pil ömrü ve özellik seti daha sınırlıdır.',
        suits: 'Hafiften orta dereceye; gizliliği ön planda tutan, ince parçaları rahat kullanabilen kişiler.',
        visibility: { level: 5, label: 'Neredeyse görünmez' },
        power: 'Hafif → orta-ileri (kanal boyutuna bağlı)',
        rechargeable: 'Nadir',
        wireless: 'Sınırlı',
        handling: 'Zor (küçük parçalar)',
        care: 'Yüksek',
      },
      {
        id: 'iic',
        code: 'IIC',
        name: 'Görünmez kanal içi',
        short: 'Invisible-in-Canal',
        description: 'Kulak kanalına derin yerleşen küçük bir tasarımdır. Görünürlüğü ve yerleşim derinliği kulak anatomisine ve modele bağlıdır; her kulak için uygun olmayabilir.',
        suits: 'Hafiften orta dereceye; kulak kanalı uygun olan ve çok az görünen bir çözüm isteyenler.',
        visibility: { level: 5, label: 'Çok az görünür' },
        power: 'Hafif → orta',
        rechargeable: 'Nadir',
        wireless: 'Çok sınırlı',
        handling: 'Zor (küçük parçalar)',
        care: 'Yüksek',
        note: 'Kulak kanalı ölçüsü ve şekli uygun olmalıdır.',
      },
    ],
    systems: {
      title: 'Form faktöründen bağımsız sistem seçenekleri',
      items: [
        {
          name: 'CROS / BiCROS',
          text: 'Tek taraflı işitme kaybında, duymayan kulak tarafındaki mikrofon sesi kablosuz olarak diğer kulaktaki cihaza aktarır. BiCROS, iyi duyan kulakta da kayıp varsa kullanılır. Ayrı bir cihaz türü değil, bir sistem özelliğidir.',
        },
        {
          name: 'Power / Super Power',
          text: 'İleri ve çok ileri derece kayıplar için yüksek çıkış gücü sunan, genellikle kulak arkası (BTE) gövdeli modeller. Kişiye özel kulak kalıbıyla kullanılır.',
        },
        {
          name: 'Çocuklar için seçenekler',
          text: 'Çocuklarda kulak büyüdükçe kalıbın yenilenebildiği, dayanıklı ve okul sistemleriyle uyumlu kulak arkası modeller tercih edilir. Değerlendirme ve takip, çocuk odyolojisi süreciyle birlikte yürütülür.',
        },
      ],
    },
    disclaimer: 'Bu tablo üreticilerin genel sınıflandırmasına dayanır. Her model her telefonla çalışmaz, her kulak her türe uygun değildir ve sonuçlar kişiden kişiye değişir. Kesin öneri, işitme değerlendirmesi sonrasında verilir.',
    askCta: 'Bu tür hakkında bilgi al',
    sourcesNote: 'Genel karşılaştırmadır. Güç, bağlantı ve şarj seçeneklerini seçilen modelin teknik bilgileriyle doğrularız.',
  },

  brands: {
    eyebrow: 'Markalar ve teknolojiler',
    h2: 'Sektörün önde gelen markalarını yakından tanıyoruz.',
    lead: 'Dünyada işitme cihazı üretimi birkaç büyük grup altında toplanır. Marka seçiminden önce cihaz türünü, güç ihtiyacını ve günlük kullanım beklentinizi netleştiriyor; ardından size uygun seçenekleri tarafsız biçimde karşılaştırıyoruz.',
    featured: [
      { name: 'Phonak', group: 'Sonova', text: 'İsviçre merkezli Sonova grubunun markası. Gürültüde konuşma anlaşılırlığına odaklanan platformları ve geniş bağlantı ekosistemiyle bilinir.' },
      { name: 'Oticon', group: 'Demant', text: 'Danimarka merkezli Demant grubunun markası. Beynin sesi doğal biçimde işlemesini hedefleyen "BrainHearing" yaklaşımıyla tanınır.' },
      { name: 'Widex', group: 'WS Audiology', text: 'Danimarka kökenli; doğal ve saf ses karakteriyle, özellikle müzik ve sessiz ortam performansıyla anılır.' },
      { name: 'Bernafon', group: 'Demant', text: 'İsviçre kökenli, Demant grubuna bağlı marka. Konuşma anlaşılırlığı ile dinleme konforunu dengeleyen hibrit ses işleme yaklaşımı sunar.' },
      { name: 'Signia', group: 'WS Audiology', text: 'Almanya kökenli; önceden Siemens işitme cihazları olarak bilinen marka. Konuşma odaklı işleme ve şık tasarımlarıyla öne çıkar.' },
      { name: 'ReSound', group: 'GN', text: 'Danimarka merkezli GN grubunun markası. Uyumlu telefonlardan işitme cihazına kablosuz ses aktarımı sunan markalardandır.' },
    ],
    groupsTitle: 'Markalar hangi gruba bağlı?',
    groups: [
      { group: 'Sonova', brands: ['Phonak', 'Unitron'], note: 'İsviçre' },
      { group: 'Demant', brands: ['Oticon', 'Bernafon', 'Philips Hearing Solutions'], note: 'Danimarka' },
      { group: 'WS Audiology', brands: ['Widex', 'Signia'], note: 'Danimarka / Almanya' },
      { group: 'GN', brands: ['ReSound', 'Beltone'], note: 'Danimarka' },
      { group: 'Starkey', brands: ['Starkey'], note: 'ABD, bağımsız' },
    ],
    disclaimer: 'Bu bölüm bilgilendirme amaçlıdır; marka adları ilgili şirketlerin tescilli markalarıdır. Merkezimizde hangi markaların uygulandığı, stok ve fiyat bilgisi için lütfen bize ulaşın.',
    techTitle: 'Güncel teknolojiler: ne işe yarar?',
    tech: [
      { name: 'Gürültüde konuşma işleme', text: 'Cihaz ortamı sürekli analiz eder, konuşmayı öne çıkarıp arka plan gürültüsünü bastırır. Bazı platformlarda yapay zekâ destekli işleme kullanılır; sonuçlar ortama ve modele bağlıdır.' },
      { name: 'Şarj edilebilir pil', text: 'Gece şarj ünitesine bırakılır; tek kullanımlık pil değiştirme ihtiyacını azaltır. Küçük parçaları tutmakta zorlananlar için önemli bir kolaylıktır.' },
      { name: 'Bluetooth ve LE Audio / Auracast', text: 'Uyumlu telefonlardan görüşme ve müzik sesi cihaza aktarılabilir. TV için ek aksesuar gerekebilir. Auracast destekli modeller, uyumlu ortamlarda yayınları doğrudan alabilir. Uyumluluk telefon modeline göre değişir.' },
      { name: 'Uygulama ile kişiselleştirme', text: 'Ses seviyesi, program ve bazı ince ayarlar telefon uygulamasından yapılır; bazı markalarda uzaktan ayar desteği de bulunur.' },
      { name: 'Telecoil (T-bobin)', text: 'Cami, salon ve gişe gibi indüksiyon döngüsü bulunan ortamlarda sesi doğrudan alır. Modele göre bulunur.' },
      { name: 'Tinnitus (çınlama) desteği', text: 'Birçok cihazda çınlamayı maskelemeye yardımcı ses programları vardır; uzman değerlendirmesiyle kullanılır.' },
    ],
  },

  services: {
    eyebrow: 'Hizmetler',
    h2: 'İlk görüşmeden düzenli bakıma kadar tek merkezden.',
    lead: 'İhtiyaçlarınızı dinliyor, uygun seçenekleri açıklıyor ve kullanım sürecinizi takip ediyoruz. Cihaz seçimi kadar uygulama, bakım ve desteğe de önem veriyoruz.',
    items: [
      {
        id: 'test',
        icon: 'ear',
        title: 'İşitme değerlendirmesi',
        text: 'Görüşme ve işitme testiyle mevcut durumunuzu birlikte anlıyoruz. Sonuçları sade bir dille açıklıyor, seçenekleri buna göre sunuyoruz.',
        ...(canShow(b.claims.freeHearingTest) ? { badge: 'Ücretsiz' } : {}),
      },
      { id: 'secim', icon: 'sliders', title: 'Cihaz seçimi ve deneme', text: 'İşitme kaybı derecesi, kulak yapısı ve yaşam tarzınıza göre uygun türleri karşılaştırıyor; cihazı yerinde deneyerek karar vermenizi sağlıyoruz.' },
      { id: 'uygulama', icon: 'settings', title: 'Uygulama ve ince ayar', text: 'Cihaz işitme eğrinize göre programlanır. İlk haftalarda geri bildiriminize göre kademeli ayarlarla en rahat dinleme noktasını buluyoruz.' },
      { id: 'kalip', icon: 'mold', title: 'Kişiye özel kulak kalıbı', text: 'Kulak izinizi alıp kulak yapınıza tam oturan kalıp üretiyoruz. Kalıbın uyumunu, ses iletimini ve kullanım konforunu birlikte kontrol ediyoruz.' },
      {
        id: 'pil',
        icon: 'battery',
        title: 'Pil, filtre ve aksesuar',
        text: 'Cihazınıza uygun pil, alıcı filtresi, dome ve temizlik ürünleri için destek veriyoruz. Uyumluluk ve stok durumunu birlikte kontrol ediyoruz. Şarj üniteleri ve bağlantı aksesuarları için de yardımcı oluyoruz.',
      },
      { id: 'bakim', icon: 'wrench', title: 'Bakım, servis ve takip', text: 'Periyodik temizlik, nem giderme ve kontrol. Arıza durumunda tespit yapıp yetkili servis sürecini sizin adınıza takip ediyoruz.' },
      ...(canShow(b.claims.sgkContracted)
        ? [{ id: 'sgk', icon: 'file', title: 'SGK süreci desteği', text: 'SGK anlaşmalı merkez olarak rapor ve reçete sürecinde size yol gösteriyor, gerekli belgeleri birlikte hazırlıyoruz. Katkı payı ve koşullar güncel mevzuata göre değişir.' }]
        : []),
    ],
  },

  earMold: {
    eyebrow: 'Kulak kalıbı',
    h2: 'Kulağınıza göre üretilen kalıp: küçük parça, büyük fark.',
    lead: 'Kulak kalıbı, cihazın sesini kulağınıza taşıyan ve cihazı yerinde tutan kişiye özel parçadır. Birçok kulak arkası cihazda ve bazı RIC uygulamalarında kullanılır; seçim güç ihtiyacına ve kulak yapısına bağlıdır. Doğru ölçü ve doğru malzeme; konforu, ses kalitesini ve ötme kontrolünü doğrudan etkiler.',
    steps: [
      { title: 'Kulak kanalı kontrolü', text: 'Ölçü öncesi kulak kanalı incelenir; kir veya tahriş varsa önce bunun giderilmesi gerekir.' },
      { title: 'Kulak izi alma', text: 'Kanala küçük bir koruyucu yerleştirilir, ardından yumuşak silikon ölçü malzemesi uygulanır. Birkaç dakika içinde sertleşir. İşlem uzman tarafından uygulanır; rahatsızlık hissederseniz hemen belirtmeniz istenir.' },
      { title: 'Üretim', text: 'Alınan iz; cihaz türüne, güç ihtiyacına ve kullanım amacına göre seçilen malzemeyle kalıba dönüştürülür.' },
      { title: 'Uyum kontrolü ve teslim', text: 'Kalıp kulakta denenir, gerekirse ince düzeltmeler yapılır. Takma-çıkarma ve temizlik uygulamalı olarak gösterilir.' },
    ],
    types: [
      { name: 'Sert akrilik kalıp', text: 'Dayanıklı ve kolay temizlenir; takıp çıkarması pratiktir. Uzun süreli kullanımda şeklini korur.' },
      { name: 'Yumuşak silikon kalıp', text: 'Daha esnek ve sızdırmazlığı yüksektir; güçlü cihazlarda ötmeyi azaltmak için tercih edilir. Çocuklarda yaygın kullanılır.' },
      { name: 'Skeleton / yarım kalıp', text: 'Kulak kepçesinin yalnızca bir kısmını kaplayan, daha hafif ve havadar seçenekler. Hafif–orta kayıplarda kullanılır.' },
      { name: 'Standart dome', text: 'Alıcısı kanalda (RIC) cihazlarda kullanılan hazır silikon uçlar. Açık ve kapalı seçenekleri vardır; boy ve tip, uygulamaya göre seçilir.' },
    ],
    care: [
      'Cihazı ve kalıbı üreticinin talimatına göre yumuşak, kuru bezle temizleyin. Alıcı veya elektronik içeren parçaları suya sokmayın.',
      'Yalnızca elektronik içermeyen, hortumlu BTE kalıpları için önerilen yıkama yöntemini kullanın; tekrar bağlamadan önce tamamen kurutun. Temizlik yöntemini merkezimizde uygulamalı öğrenin.',
      'Kulak yapısı zamanla değişir; kalıp gevşediğinde veya ötme başladığında yenilenmesi gerekebilir.',
    ],
    distinction: 'İşitme cihazı kalıbı ile yüzücü tıkacı ve gürültü koruyucu tıkaç farklı ürünlerdir. Kişiye özel koruyucu tıkaç ihtiyacınız varsa ayrıca bilgi verebiliriz.',
    cta: 'Kulak kalıbı için randevu',
  },

  process: {
    eyebrow: 'Nasıl ilerliyoruz?',
    h2: 'İlk görüşmeden düzenli takibe dört adım.',
    lead: 'İhtiyacınıza göre planlanan her adımda ne yapıldığını ve neden yapıldığını anlatır, kullanım deneyiminizi takip ederiz.',
    steps: [
      { title: 'Görüşme', text: 'Beklentinizi, günlük ortamlarınızı ve varsa mevcut cihaz deneyiminizi dinleriz. Telefon veya WhatsApp ile randevu alabilirsiniz.' },
      { title: 'Değerlendirme ve seçenekler', text: 'İşitme testi ve kulak kontrolünün ardından uygun cihaz türlerini karşılaştırır, deneme imkânı sunarız.' },
      { title: 'Uygulama ve kişiselleştirme', text: 'Seçilen cihaz işitme eğrinize göre ayarlanır; gerekirse kulak kalıbı üretilir. Kullanım ve temizlik uygulamalı gösterilir.' },
      { title: 'Kontrol ve bakım', text: 'İlk haftalarda ince ayar randevuları, ardından düzenli kontrol ve bakım. Sorularınız için telefon veya WhatsApp üzerinden ulaşabilirsiniz.' },
    ],
    note: 'İşitme cihazı işitmeyi destekler; işitme kaybının nedenine yönelik hekim değerlendirmesinin yerini almaz. Sonuçlar kişiye, kaybın türüne ve kullanım düzenine göre değişir.',
  },

  center: {
    eyebrow: 'Merkezimiz',
    h2: 'Keçiören Ayvalı Caddesi\'nde, ulaşımı kolay bir merkez.',
    lead: 'Ferah bekleme alanı ve ayrı görüşme odasıyla, işitme değerlendirmesinden cihaz ayarına kadar tüm süreç aynı merkezde tamamlanır.',
    facts: [
      { label: 'Adres', value: b.address.line },
      { label: 'Telefon', value: b.phone.display },
      ...(canShow(b.hours) ? [{ label: 'Çalışma saatleri', value: 'Pazartesi–Cumartesi 09:00–18:00' }] : []),
    ],
    teamTitle: 'Uzman ekibimiz',
    teamText: 'İlk görüşmede ihtiyaçlarınızı dinliyor, cihaz uygulaması ve takip randevularını birlikte planlıyoruz.',
    galleryLabel: 'Merkez fotoğrafları',
    photos: [
      { key: 'ofis-6', alt: 'Ayaz İşitme Cihazları mağaza cephesi, Ayvalı Caddesi, Keçiören', caption: 'Ayvalı Caddesi üzerindeki merkezimiz' },
      { key: 'ofis-1', alt: 'Ayaz İşitme Merkezi görüşme odası ve ekip üyesi', caption: 'Görüşme ve uygulama odası' },
      { key: 'ofis-3', alt: 'Bekleme alanı: koltuklar, bitkiler ve cadde manzaralı vitrin', caption: 'Bekleme alanı' },
      { key: 'ofis-5', alt: 'Görüşme odası: uzman masası, pil standı ve duvarda işitme anatomisi posteri', caption: 'Görüşme odası' },
      { key: 'ofis-7', alt: 'Bekleme alanının girişten görünümü', caption: 'Giriş ve bekleme alanı' },
      { key: 'ofis-8', alt: 'Görüşme odasının kapıdan görünümü', caption: 'Görüşme odası' },
    ],
    directionsCta: 'Yol tarifi al',
  },

  reviews: {
    eyebrow: 'Google yorumları',
    h2: 'Kullanıcılarımız ne diyor?',
    lead: 'Google işletme profilimizdeki deneyimleri okuyabilir, kendi deneyiminizi paylaşabilirsiniz.',
    ratingLabel: 'Google puanı',
    countLabel: (n) => `${n} yorum`,
    seeAll: 'Tüm yorumları Google\'da gör',
    write: 'Yorum yaz',
    attribution: 'Yorumlar Google tarafından sağlanır.',
    loading: 'Yorumlar yükleniyor…',
    offline: 'Yorumlarımız Google\'da',
    offlineText: 'Google işletme profilimizdeki güncel puan ve yorumları görmek için bağlantıyı kullanın.',
    apiNote: 'Burada Google tarafından seçilen yorumlar gösterilir. Güncel yorumların tamamını Google Haritalar üzerinde okuyabilirsiniz.',
  },

  faq: {
    eyebrow: 'Sık sorulan sorular',
    h2: 'Merak edilenler',
    lead: 'Aklınızdaki soru burada yoksa telefon veya WhatsApp ile bize yazın; ekibimiz yardımcı olsun.',
    items: [
      { q: 'İşitme cihazı seçimi nasıl yapılır?', a: 'Önce işitme testi ve kulak kontrolü yapılır. Kaybın derecesi ve türü, kulak kanalı yapısı, el becerisi, gözlük/maske kullanımı ve günlük ortamlarınız (kalabalık, telefon, TV) birlikte değerlendirilir. Buna göre uygun cihaz türleri ve teknoloji seviyeleri karşılaştırılır; cihazı deneyerek karar verirsiniz.' },
      { q: 'Kulak içi mi, kulak arkası mı daha iyi?', a: 'Tek bir "en iyi" yoktur. Kulak arkası ve alıcısı kanalda modeller daha geniş güç aralığı, daha uzun pil ömrü ve daha kolay kullanım sunar. Kulak içi modeller görünürlük açısından avantajlıdır ancak kulak kiri ve neme daha açıktır. Karar, kayıp derecesi ve kulak yapınıza göre verilir.' },
      { q: 'Şarjlı mı, pilli mi tercih etmeliyim?', a: 'Şarjlı modeller gece şarj ünitesine bırakılır; küçük pilleri tutmakta zorlananlar için pratiktir. Pilli modellerde ise pil değiştirerek kesintisiz kullanım mümkündür ve şarj ünitesine bağımlılık yoktur. Yaşam tarzınıza göre birlikte karar veririz.' },
      { q: 'Cihaz telefonuma bağlanır mı?', a: 'Günümüz modellerinin çoğu Bluetooth ile telefon görüşmesi, müzik ve video sesini doğrudan aktarır. Ancak uyumluluk telefonun modeline, işletim sistemine ve cihazın bağlantı standardına göre değişir; görüşmede telefonunuzla uyum kontrolü yapıyoruz.' },
      { q: 'Kulak kalıbı neden gerekli, nasıl alınır?', a: 'Kalıp cihazı kulakta sabit tutar, sesi kaçırmadan iletir ve ötmeyi azaltır. Kulak kanalına küçük bir koruyucu yerleştirilip yumuşak silikon ölçü malzemesi uygulanır; birkaç dakikada sertleşir. İşlem uzman tarafından uygulanır; kalıp kulak yapınıza özel üretilir ve teslimde uyumu kontrol edilir.' },
      { q: 'İlk kullanımda alışma süreci nasıl olur?', a: 'Beyin, uzun süredir duymadığı sesleri yeniden öğrenir. İlk günlerde kendi sesiniz ve ortam sesleri farklı gelebilir. Kademeli kullanım süresi ve ilk haftalardaki ince ayar randevularıyla çoğu kullanıcı birkaç hafta içinde belirgin şekilde alışır.' },
      { q: 'Bakım nasıl yapılır, filtre ne sıklıkla değişir?', a: 'Temizleme, kurutma ve saklamada cihazınızın kullanım kılavuzunu izleyin. Filtre ve dome değişim sıklığı modele ve kulak kiri birikimine göre değişir; önerilen süreyi ve değişim yöntemini uygulamalı gösteriyoruz.' },
      { q: 'İlk randevuda neler yapılır, ne getirmeliyim?', a: 'Görüşme, kulak kontrolü ve işitme testi yapılır; sonuçlar açıklanır ve seçenekler anlatılır. Varsa önceki işitme testi sonuçlarınızı, kullandığınız cihazı ve SGK süreci için kimliğinizi getirmeniz yeterlidir.' },
      { q: 'İşitme cihazı fiyatını ne belirler?', a: 'Fiyat; cihazın türünden çok teknoloji seviyesine (gürültü işleme, bağlantı, şarj), kanal sayısına ve ek hizmetlere göre değişir. Değerlendirme sonrası ihtiyacınıza uygun farklı seviyelerde net fiyat bilgisi veriyoruz.' },
      ...(canShow(b.claims.sgkContracted)
        ? [{ q: 'SGK işitme cihazı için ne kadar ödüyor, süreç nasıl işler?', a: 'SGK, sağlık kurulu raporu ve reçete şartıyla belirli tutarda katkı sağlar; tutarlar ve koşullar Sağlık Uygulama Tebliği ile güncellenir. SGK anlaşmalı merkez olarak belge sürecinde yol gösteriyor, güncel koşulları görüşmede paylaşıyoruz.' }]
        : []),
    ],
  },

  contact: {
    eyebrow: 'İletişim ve randevu',
    h2: 'Bir görüşme için bize ulaşın.',
    lead: 'Telefon veya WhatsApp ile hemen; ya da kısa formu bırakın, sizi arayalım. Randevu talebi, ekibimiz sizi arayıp saat teyit ettiğinde kesinleşir.',
    form: {
      title: 'Randevu talebi',
      name: 'Ad Soyad',
      phone: 'Telefon',
      time: 'Sizi ne zaman arayalım?',
      timeOptions: ['Fark etmez', 'Sabah (09:00–12:00)', 'Öğleden sonra (12:00–15:00)', 'Akşamüstü (15:00–18:00)'],
      note: 'Sağlık bilgisi, rapor veya odyogram istemiyoruz; bunları görüşmede birlikte değerlendiririz.',
      consent: 'Randevu için iletişim bilgilerimin işlenmesine ilişkin aydınlatma metnini okudum.',
      consentLink: 'Aydınlatma metni',
      submit: 'Randevu Talebi Gönder',
      submitWhatsapp: 'WhatsApp ile Gönder',
      sending: 'Gönderiliyor…',
      successTitle: 'Talebiniz alındı',
      successText: 'Ekibimiz uygun bir randevu saati belirlemek için sizinle iletişime geçecek. Tercih ettiğiniz saat aralığını dikkate alacağız.',
      errorTitle: 'Gönderilemedi',
      errorText: 'Bir sorun oluştu. Lütfen telefon veya WhatsApp ile ulaşın.',
      fallbackNotice: 'Form, talebinizi hazır bir WhatsApp mesajına dönüştürür; göndermek için WhatsApp\'ta onaylamanız yeterlidir.',
      validation: {
        name: 'Lütfen adınızı ve soyadınızı yazın.',
        phone: 'Lütfen geçerli bir telefon numarası yazın (ör. 05xx xxx xx xx).',
        consent: 'Devam etmek için aydınlatma metnini onaylayın.',
        time: 'Lütfen bir zaman aralığı seçin.',
      },
    },
    info: {
      address: 'Adres',
      phone: 'Telefon',
      whatsapp: 'WhatsApp',
      email: 'E-posta',
      hours: 'Çalışma saatleri',
      hoursValue: 'Pazartesi–Cumartesi 09:00–18:00',
      closed: 'Pazar kapalı',
      directions: 'Yol tarifi',
      loadMap: 'Haritayı yükle',
      mapNote: 'Harita Google tarafından sağlanır; yüklendiğinde Google\'ın çerez politikası geçerli olur.',
    },
  },

  footer: {
    legal: b.legalName,
    privacy: 'Gizlilik ve KVKK',
    cookies: 'Çerez tercihleri',
    rights: 'Tüm hakları saklıdır.',
    quick: 'Hızlı erişim',
    contact: 'İletişim',
    disclaimer: 'Bu sitedeki bilgiler genel bilgilendirme amaçlıdır; tıbbi tanı veya tedavi yerine geçmez. Marka adları ilgili şirketlerin tescilli markalarıdır.',
  },

  consent: {
    title: 'Çerez tercihleri',
    text: 'Sitemiz zorunlu çerezlerle çalışır. Ziyaret istatistikleri ve reklam ölçümü için kullanılan isteğe bağlı çerezler yalnızca izin verirseniz yüklenir.',
    acceptAll: 'Tümünü kabul et',
    rejectAll: 'Yalnızca zorunlu',
    manage: 'Tercihleri yönet',
    save: 'Seçimi kaydet',
    categories: [
      { key: 'necessary', label: 'Zorunlu', text: 'Sitenin çalışması ve tercihlerinizin hatırlanması için gerekli. Kapatılamaz.', locked: true },
      { key: 'analytics', label: 'Analitik', text: 'Sayfanın nasıl kullanıldığını anlamamızı sağlar (Google Analytics). Kullanım ve cihaz bilgileri işlenebilir; formdaki adınız ve telefonunuz analitiğe gönderilmez.' },
      { key: 'marketing', label: 'Pazarlama', text: 'Reklam kampanyalarının etkisini ölçmek için kullanılır (Google Ads, Meta). Yalnızca etkinleştirilmiş ölçüm hizmetleri, izninizle çalışır.' },
    ],
    reopen: 'Çerez tercihleri',
    policyLink: 'Çerez politikası',
  },

  mobileBar: { call: 'Ara', whatsapp: 'WhatsApp', directions: 'Yol tarifi' },

  common: {
    skip: 'İçeriğe geç',
    menu: 'Menü',
    close: 'Kapat',
    back: 'Geri',
    next: 'Sonraki',
    prev: 'Önceki',
    learnMore: 'Bilgi al',
    new: 'Yeni',
  },
};
