import type { SiteContent } from './types';
import { business, canShow } from '../config/business';

const b = business;

export const tr: SiteContent = {
  locale: 'tr',
  htmlLang: 'tr',
  seo: {
    title: 'Keçiören İşitme Cihazı Merkezi | Ayaz İşitme Merkezi · Ankara',
    description:
      'Ankara Keçiören\'de işitme cihazı seçimi, kişiye özel uygulama, kulak kalıbı, pil ve bakım. Kulak arkası ve kulak içi seçenekleri inceleyin; randevu talep edin.',
    ogAlt: 'Ayaz İşitme Merkezi — Keçiören, Ankara',
  },
  nav: [
    { href: '#cihazlar', label: 'Cihazlar' },
    { href: '#hizmetler', label: 'Hizmetler' },
    { href: '#merkezimiz', label: 'Merkezimiz' },
    { href: '#yorumlar', label: 'Yorumlar' },
    { href: '#iletisim', label: 'İletişim' },
  ],
  navCta: 'Randevu Talep Et',
  langSwitch: { label: 'EN', href: '/en/', hreflang: 'en' },

  hero: {
    eyebrow: 'Ankara · Keçiören',
    h1: 'Keçiören\'de size uygun işitme çözümleri.',
    sub: 'Cihaz seçimi, kişiye özel uygulama ve düzenli bakım sürecinde yanınızdayız. Kulak arkası ve kanal içi seçenekleri, işitme ihtiyaçlarınıza ve günlük yaşamınıza göre birlikte değerlendiriyoruz.',
    ctaPrimary: 'Randevu Talep Et',
    ctaSecondary: 'Cihazları Keşfet',
    trust: [
      ...(canShow(b.claims.freeHearingTest) ? ['Ücretsiz işitme testi'] : ['İşitme değerlendirmesi']),
      'Kişiye özel kulak kalıbı',
      ...(canShow(b.claims.sgkContracted) ? ['SGK anlaşmalı merkez'] : []),
      'Pil, filtre ve bakım',
    ],
    deviceCaption: 'Temsili RIC (alıcısı kanalda) işitme cihazı, 312 pilli',
  },

  explorer: {
    eyebrow: 'Yakından inceleyin',
    h2: 'Bir işitme cihazını yakından tanıyın.',
    lead: 'Üç temel cihaz türünü döndürün, yakınlaştırın, pil kapağını açın ve parçalarını ayrı ayrı inceleyin. Her parçanın ne işe yaradığını öğrenin; merkezimizde gerçek cihazları elinize alıp deneyebilirsiniz.',
    representativeNote: 'Temsili modeller. Parçaların ayrılması anlatım amaçlıdır; cihazı kendiniz sökmeyin. Tasarım markaya ve modele göre değişir.',
    controls: {
      rotate: 'Döndür',
      zoom: 'Yakınlaştır',
      reset: 'Başa dön',
      explode: 'Parçaları ayır',
      autoRotate: 'Otomatik döndürme',
      explodeLabel: 'Ayrışma oranı',
      door: 'Pil kapağı',
      modelLabel: 'Cihaz türü',
    },
    models: [
      {
        id: 'ric',
        label: 'RIC',
        sub: 'Alıcısı kanalda · 312 pil',
        caption: 'Temsili RIC (alıcısı kanalda) işitme cihazı, 312 pilli',
        hotspots: [
          { id: 'mics', title: 'Mikrofonlar', text: 'Ortamdaki sesi alır. Çoğu modelde iki mikrofon bulunur; böylece cihaz konuşmanın hangi yönden geldiğini ayırt edebilir.' },
          { id: 'body', title: 'Gövde ve işlemci', text: 'Kulak arkasına oturan ince gövde; içindeki işlemci sesi analiz eder, gürültüyü azaltır ve konuşmayı öne çıkarır.' },
          { id: 'button', title: 'Kontrol düğmesi', text: 'Ses seviyesini veya programı değiştirmek için kullanılır. Birçok model telefon uygulamasıyla da kontrol edilir.' },
          { id: 'wire', title: 'İnce alıcı kablosu', text: 'Gövdeden kulak kanalına giden neredeyse görünmez bağlantı. Uzunluğu kulak yapınıza göre seçilir.' },
          { id: 'receiver', title: 'Alıcı (hoparlör)', text: 'Kulak kanalının içinde yer alır ve işlenmiş sesi kulağa iletir. Güç seviyesi işitme kaybına göre seçilir.' },
          { id: 'dome', title: 'Dome veya kulak kalıbı', text: 'Alıcıyı kulakta tutan yumuşak uç. Standart dome ya da kişiye özel üretilen kulak kalıbı kullanılabilir.' },
          { id: 'battery-door', title: 'Pil kapağı', text: 'Gövdenin alt ucundaki çekmece kapak. Tırnakla çekilince pimi etrafında öne döner ve pili yuvasından dışarı çıkarır; kapatınca pil yerine geri girer. Kapak hafif aralık bırakıldığında cihaz kapanır ve pil tasarrufu sağlar.' },
          { id: 'battery', title: 'Pil (312, kahverengi)', text: 'Çinko-hava düğme pil. Bandı çıkarıldıktan sonra havayla çalışmaya başlar; kullanım süresi cihaza ve günlük kullanıma göre değişir.' },
        ],
      },
      {
        id: 'bte',
        label: 'BTE',
        sub: 'Kulak arkası · 13 pil',
        caption: 'Temsili BTE (kulak arkası) işitme cihazı, 13 pilli, kulak kalıplı',
        hotspots: [
          { id: 'mics', title: 'Mikrofonlar', text: 'Gövdenin üst kısmındaki iki mikrofon girişi sesi alır ve yönünü ayırt eder.' },
          { id: 'body', title: 'Gövde ve işlemci', text: 'Daha büyük gövde, daha güçlü amplifikasyon ve daha uzun pil ömrü sağlar; ileri derece kayıplarda da kullanılır.' },
          { id: 'button', title: 'Program ve ses düğmesi', text: 'Program değiştirme ve ses ayarı için büyük, kolay hissedilen düğmeler.' },
          { id: 'hook', title: 'Kulak kancası', text: 'Gövdenin tepesine vidalanan sert, şeffaf ve kavisli parça; cihazı kulak kepçesinin üzerinde tutar ve sesi hortuma iletir.' },
          { id: 'tube', title: 'Hortum', text: 'Kancanın ucuna geçirilen ve kulak kalıbına takılan şeffaf ses hortumu. Zamanla sertleşir ve düzenli aralıklarla yenilenir.' },
          { id: 'earmold', title: 'Kulak kalıbı', text: 'Kulak izinizden üretilen, kulağa tam oturan parça. Sesi kanala iletir, ötmeyi azaltır; sert akrilik veya yumuşak silikon olabilir.' },
          { id: 'battery-door', title: 'Pil kapağı', text: 'Gövdenin alt ucundaki çekmece kapak; açılınca pil kapakla birlikte dışarı çıkar. Büyük boyu sayesinde pil değişimi kolaydır.' },
          { id: 'battery', title: 'Pil (13, turuncu)', text: 'Daha büyük çinko-hava pil; genellikle daha uzun kullanım süresi sunar.' },
        ],
      },
      {
        id: 'cic',
        label: 'CIC',
        sub: 'Tamamen kanal içi · 10 pil',
        caption: 'Temsili CIC (tamamen kanal içi) işitme cihazı, 10 pilli',
        hotspots: [
          { id: 'shell', title: 'Kabuk', text: 'Kulak kanalınızın izinden üretilen, kişiye özel kabuk. Kanalın derinine yerleşir; dışarıdan çok az görünür.' },
          { id: 'faceplate', title: 'Ön yüz', text: 'Kanal girişine bakan yüzey; mikrofon, pil kapağı ve çıkarma ipini taşır.' },
          { id: 'mic', title: 'Mikrofon girişi', text: 'Ön yüzdeki küçük açıklık. Kulak kepçesinin doğal biçimi sayesinde ses yönü korunur.' },
          { id: 'battery-door', title: 'Pil kapağı', text: 'Ön yüzdeki minik menteşeli kapak; tırnakla açılınca pil kapakla birlikte dışarı çıkar. Küçük parçaları tutmakta zorlananlar için değişim pratik olmayabilir.' },
          { id: 'battery', title: 'Pil (10, sarı)', text: 'En küçük çinko-hava pil. Küçük boyutu nedeniyle kullanım süresi diğer türlere göre daha kısadır.' },
          { id: 'vent', title: 'Havalandırma kanalı', text: 'Kabuk boyunca uzanan ince kanal; basınç hissini ve kendi sesinizin boğuk duyulmasını azaltır.' },
          { id: 'pull-string', title: 'Çıkarma ipi', text: 'Cihazı kulaktan kolayca çıkarmanızı sağlayan ince naylon ip.' },
          { id: 'receiver-outlet', title: 'Ses çıkışı ve kir filtresi', text: 'Kanala bakan uçtaki ses çıkışı; kulak kirine karşı değiştirilebilir bir filtreyle korunur.' },
        ],
      },
    ],
    fallbackTitle: '3B görünüm bu cihazda kullanılamıyor',
    fallbackText: 'Tarayıcı bu oturumda 3B görüntüleme için gereken WebGL2 bağlantısını başlatamadı. Parça açıklamalarını aşağıda okuyabilir, cihazları merkezimizde inceleyebilirsiniz.',
    loadErrorTitle: '3B model şu anda yüklenemedi',
    loadErrorText: 'Yükleme sırasında bir sorun oluştu. Sayfayı yenileyerek tekrar deneyebilirsiniz; cihaz görselleri ve parça açıklamaları kullanılabilir.',
    reloadLabel: 'Sayfayı yenile',
    keyboardHint: 'Klavye: ok tuşlarıyla döndürün, + / − ile yakınlaştırın, R ile başa dönün, E ile parçaları ayırın, B ile pil kapağını açın. Dokunmatik ekranda yatay sürükleyerek döndürün.',
    loading: '3B model hazırlanıyor…',
    cta: 'Cihazları yerinde deneyin',
  },

  devices: {
    eyebrow: 'İşitme cihazı türleri',
    h2: 'Kulak arkası mı, kulak içi mi? Seçenekleri tanıyın.',
    lead: 'İşitme cihazları yerleşim biçimine göre ayrılır. Şarjlı olması veya Bluetooth desteği ise ayrı birer özelliktir ve bulunabilirliği modele göre değişir. Aşağıdaki karşılaştırma genel bir rehberdir; doğru seçim işitme değerlendirmesi, kulak yapısı ve günlük ihtiyaçlarınıza göre yapılır.',
    tableHeaders: {
      visibility: 'Görünürlük',
      power: 'Güç aralığı',
      rechargeable: 'Şarjlı seçenek',
      wireless: 'Kablosuz bağlantı',
      handling: 'Kullanım kolaylığı',
      care: 'Bakım ihtiyacı',
      suits: 'Genellikle kimler için',
    },
    types: [
      {
        id: 'bte',
        code: 'BTE',
        name: 'Kulak arkası',
        short: 'Behind-the-Ear',
        description: 'Tüm elektronik parçalar kulak arkasındaki gövdede yer alır; ses bir hortum ve uygun kalıp veya uç aracılığıyla kulağa iletilir. Farklı güç seviyeleri ve kontrol seçenekleri bulunur.',
        suits: 'Hafiften çok ileri dereceye kadar geniş bir aralık; büyük düğme ve pil isteyenler; çocuklar için sık tercih edilen tür.',
        visibility: { level: 5, label: 'Görünür' },
        power: 'Hafif → çok ileri',
        rechargeable: 'Yaygın',
        wireless: 'Yaygın',
        handling: 'Çok kolay',
        care: 'Düşük–orta (hortum ve kalıp temizliği)',
      },
      {
        id: 'ric',
        code: 'RIC / RITE',
        name: 'Alıcısı kanalda',
        short: 'Receiver-in-Canal',
        description: 'Küçük gövde kulak arkasında, alıcı (hoparlör) ise ince bir kabloyla kulak kanalının içindedir. Kompakt gövdesi ve farklı alıcı seçenekleriyle birçok ihtiyaca uyarlanabilir.',
        suits: 'Hafiften çok ileri dereceye (güçlü alıcıyla); şık ve az görünür bir cihaz isteyen yetişkinler. Alıcı gücü değiştirilebildiği için işitme değişirse uyarlanabilir.',
        visibility: { level: 3, label: 'Az görünür' },
        power: 'Hafif → çok ileri (alıcıya bağlı)',
        rechargeable: 'Çok yaygın',
        wireless: 'Çok yaygın',
        handling: 'Kolay',
        care: 'Orta (alıcı filtresi ve dome bakımı)',
      },
      {
        id: 'ite',
        code: 'ITE',
        name: 'Kulak içi',
        short: 'In-the-Ear',
        description: 'Kulak izinizden üretilen kabuk, kulak kepçesinin iç kısmını doldurur. Tam veya yarım kabuk seçenekleri vardır; kulak arkasında hiçbir parça yoktur.',
        suits: 'Hafiften ileri dereceye; gözlük veya maske kullananlar, kulak arkasında cihaz istemeyenler; tutması kolay, düğmesi büyük bir kulak içi model arayanlar.',
        visibility: { level: 4, label: 'Orta' },
        power: 'Hafif → ileri',
        rechargeable: 'Birçok modelde',
        wireless: 'Yaygın',
        handling: 'Kolay',
        care: 'Orta–yüksek (kulak kiri ve nem)',
      },
      {
        id: 'itc',
        code: 'ITC',
        name: 'Kanal içi',
        short: 'In-the-Canal',
        description: 'ITE\'den daha küçük; kulak kanalının girişine oturur ve dışarıdan yalnızca küçük bir yüzü görünür. Kişiye özel kabukla üretilir.',
        suits: 'Hafiften orta-ileri dereceye; az görünür ama yine de elle tutulup yerleştirilebilen bir model isteyenler.',
        visibility: { level: 3, label: 'Az görünür' },
        power: 'Hafif → orta-ileri',
        rechargeable: 'Sınırlı',
        wireless: 'Bazı modellerde',
        handling: 'Orta',
        care: 'Yüksek (kulak kiri ve nem)',
      },
      {
        id: 'cic',
        code: 'CIC',
        name: 'Tamamen kanal içi',
        short: 'Completely-in-Canal',
        description: 'Kulak kanalının derininde durur; görünürlüğü kulak yapısına ve modele göre değişir. Küçük boyutu nedeniyle pil ömrü ve özellik seti daha sınırlıdır.',
        suits: 'Hafiften orta-ileri dereceye (kanal boyutuna bağlı); gizliliği ön planda tutan, ince parçaları rahat kullanabilen kişiler.',
        visibility: { level: 2, label: 'Çok az görünür' },
        power: 'Hafif → orta-ileri (kanal boyutuna bağlı)',
        rechargeable: 'Nadir',
        wireless: 'Sınırlı',
        handling: 'Zor (küçük parçalar)',
        care: 'Yüksek',
      },
      {
        id: 'iic',
        code: 'IIC',
        name: 'Görünmez kanal içi',
        short: 'Invisible-in-Canal',
        description: 'Kulak kanalına derin yerleşen küçük bir tasarımdır. Görünürlüğü ve yerleşim derinliği kulak anatomisine ve modele bağlıdır; her kulak için uygun olmayabilir.',
        suits: 'Hafiften orta dereceye; kulak kanalı uygun olan ve çok az görünen bir çözüm isteyenler.',
        visibility: { level: 1, label: 'Neredeyse görünmez' },
        power: 'Hafif → orta',
        rechargeable: 'Nadir',
        wireless: 'Çok sınırlı',
        handling: 'Zor (küçük parçalar)',
        care: 'Yüksek',
        note: 'Kulak kanalı ölçüsü ve şekli uygun olmalıdır.',
      },
    ],
    systems: {
      title: 'Özel ihtiyaçlar için sistemler',
      items: [
        { id: 'cros', name: 'CROS / BiCROS', text: 'Tek taraflı kayıpta, duymayan taraftaki sesi kablosuz olarak diğer kulağa aktarır. BiCROS: iyi duyan kulakta da kayıp varsa.' },
        { id: 'power', name: 'Power / Super Power', text: 'İleri ve çok ileri derece kayıplar için yüksek çıkış gücü; genellikle kulak arkası gövde ve kişiye özel kalıpla.' },
        { id: 'kids', name: 'Çocuklar için', text: 'Dayanıklı, okul sistemleriyle uyumlu kulak arkası modeller. Kulak büyüdükçe kalıp yenilenir.' },
      ],
    },
    disclaimer: 'Bu tablo üreticilerin genel sınıflandırmasına dayanır. Her model her telefonla çalışmaz, her kulak her türe uygun değildir ve sonuçlar kişiden kişiye değişir. Kesin öneri, işitme değerlendirmesi sonrasında verilir.',
    askCta: 'Bu tür hakkında bilgi al',
    figure: {
      earLabel: (name) => `Temsili çizim: ${name} cihazın kulaktaki yerleşimi`,
      thumbAlt: (code) => `${code} işitme cihazının temsili görseli (3B modelden oluşturuldu)`,
      visibilityAria: (level, label) => `Görünürlük: 5 üzerinden ${level} (${label})`,
      behindEarNote: 'Temsili çizim. Kulak arkasındaki gövde, yerini göstermek için yarı saydam çizildi.',
      inEarNote: 'Temsili çizim. Görünüm kulak yapısına ve modele göre değişir.',
    },
    sourcesNote: 'Genel karşılaştırmadır. Güç, bağlantı ve şarj seçeneklerini seçilen modelin teknik bilgileriyle doğrularız.',
  },

  brands: {
    eyebrow: 'Markalar ve teknolojiler',
    h2: 'Başlıca işitme cihazı markaları ve bağlı oldukları gruplar.',
    lead: 'Markaların çoğu birkaç büyük üretici grubuna bağlıdır. Önce ihtiyacınızı netleştirir, ardından uygun seçenekleri tarafsız biçimde karşılaştırırız.',
    wallTitle: 'Markalar ve bağlı oldukları gruplar',
    groups: [
      { group: 'Sonova', label: 'Sonova grubu', brands: ['Phonak', 'Unitron'] },
      { group: 'Demant', label: 'Demant grubu', brands: ['Oticon', 'Bernafon', 'Philips Hearing Solutions'] },
      { group: 'WS Audiology', label: 'WS Audiology grubu', brands: ['Widex', 'Signia'] },
      { group: 'GN', label: 'GN grubu', brands: ['ReSound', 'Beltone'] },
      { group: 'Starkey', label: 'Bağımsız üretici', brands: ['Starkey'] },
    ],
    disclaimer: 'Bilgilendirme amaçlıdır; marka adları sahiplerinin tescilli markalarıdır. Merkezimizde uygulanan markalar, stok ve fiyat için bize ulaşın.',
    techTitle: 'Güncel teknolojiler',
    tech: [
      { name: 'Gürültüde konuşma', text: 'Konuşmayı öne çıkarır, arka plan gürültüsünü azaltır.' },
      { name: 'Şarj edilebilir pil', text: 'Gece şarj edilir; tek kullanımlık pil değiştirme ihtiyacını azaltır.' },
      { name: 'Bluetooth · Auracast', text: 'Telefondan görüşme ve müzik; Auracast ile uyumlu mekân yayınları.' },
      { name: 'Telefon uygulaması', text: 'Ses seviyesi ve program telefondan ayarlanır.' },
      { name: 'Telecoil (T-bobin)', text: 'İndüksiyon döngülü salonlarda sesi doğrudan alır.' },
      { name: 'Çınlama desteği', text: 'Çınlamayı maskelemeye yardımcı ses programları; uzman önerisiyle.' },
    ],
    techNote: 'Özellikler markaya, modele ve telefonunuza göre değişir.',
  },

  services: {
    eyebrow: 'Hizmetler',
    h2: 'İlk görüşmeden düzenli bakıma kadar tek merkezden.',
    lead: 'Cihaz seçimi kadar uygulama, bakım ve desteğe de önem veriyoruz.',
    items: [
      {
        id: 'test',
        icon: 'ear',
        title: 'İşitme değerlendirmesi',
        text: 'Görüşme ve işitme testiyle durumunuzu birlikte anlıyor, sonucu sade bir dille açıklıyoruz.',
        ...(canShow(b.claims.freeHearingTest) ? { badge: 'Ücretsiz' } : {}),
      },
      { id: 'secim', icon: 'sliders', title: 'Cihaz seçimi ve deneme', text: 'Size uygun türleri karşılaştırıyor, cihazı yerinde deneyerek karar vermenizi sağlıyoruz.' },
      { id: 'uygulama', icon: 'settings', title: 'Uygulama ve ince ayar', text: 'Cihazı işitme eğrinize göre programlıyor, ilk haftalarda kademeli olarak ayarlıyoruz.' },
      { id: 'kalip', icon: 'mold', title: 'Kişiye özel kulak kalıbı', text: 'Kulak izinizden, kulağınıza tam oturan kalıp üretiyoruz.' },
      { id: 'pil', icon: 'battery', title: 'Pil, filtre ve aksesuar', text: 'Cihazınıza uygun pil, filtre, dome ve temizlik ürünlerini birlikte seçiyoruz.' },
      { id: 'bakim', icon: 'wrench', title: 'Bakım, servis ve takip', text: 'Periyodik temizlik ve kontrol yapıyor, arızada yetkili servis sürecini takip ediyoruz.' },
      ...(canShow(b.claims.sgkContracted)
        ? [{ id: 'sgk', icon: 'file', title: 'SGK süreci desteği', text: 'SGK anlaşmalı merkez olarak rapor ve reçete sürecinde yol gösteriyoruz; koşullar güncel mevzuata göre değişir.' }]
        : []),
    ],
  },

  earMold: {
    eyebrow: 'Kulak kalıbı',
    h2: 'Kulağınıza göre üretilen kalıp: küçük parça, büyük fark.',
    lead: 'Cihazın sesini kulağınıza taşır ve cihazı yerinde tutar. Doğru ölçü; konforu, ses kalitesini ve ötme kontrolünü doğrudan etkiler.',
    steps: [
      { title: 'Kulak kontrolü', text: 'Ölçüden önce kulak kanalı otoskopla incelenir.' },
      { title: 'Kulak izi', text: 'Kanala küçük bir koruyucu konur, silikonla iz alınır; ardından kanal yeniden kontrol edilir.' },
      { title: 'Üretim', text: 'İz, ihtiyaca uygun malzemeyle kalıba dönüştürülür.' },
      { title: 'Uyum ve teslim', text: 'Kalıp denenir, gerekirse düzeltilir; takma ve temizlik gösterilir.' },
    ],
    imageAlt: 'İskelet tipi kulak kalıbının temsili görseli (3B modelden oluşturuldu)',
    stylesTitle: 'Kalıp biçimleri',
    stylesNote: 'Temsili görseller, aynı ölçekte; adlandırma laboratuvara göre değişebilir. Uygun biçim kulak yapısına, cihaza ve işitme kaybına göre birlikte seçilir.',
    styles: [
      { id: 'full-shell', name: 'Tam konka', text: 'Konkanın tamamını doldurur; güçlü cihazlarda sık kullanılır.' },
      { id: 'half-shell', name: 'Yarım konka', text: 'Konkanın alt kısmını doldurur; takıp çıkarması kolaydır.' },
      { id: 'skeleton', name: 'İskelet', text: 'Konka kenarını izleyen halka; ortası açık, iyi tutunur.' },
      { id: 'semi-skeleton', name: 'Yarım iskelet', text: 'Kanal ve heliks koluyla tutunur; halkanın bir kısmı açık.' },
      { id: 'canal', name: 'Kanal', text: 'Kanala ve kanal girişine oturur; konka boş kalır.' },
      { id: 'canal-lock', name: 'Kilitli kanal', text: 'Kanal kalıbına, konkanın alt kenarına dayanan küçük bir kilit.' },
      { id: 'cros', name: 'CROS (açık)', text: 'Kanalı tıkamayan açık kalıp; hortumu veya alıcıyı tutar.' },
      { id: 'micro', name: 'Kanal içi (mikro)', text: 'Tamamen kanala yerleşen küçük kalıp; sıklıkla RIC ile.' },
    ],
    materialsTitle: 'Malzeme ve RIC ucu',
    materials: [
      { id: 'acrylic', name: 'Sert akrilik', text: 'Dayanıklı, şeklini korur, kolay temizlenir.' },
      { id: 'silicone', name: 'Yumuşak silikon', text: 'Esnek ve rahat; çocuklarda sık tercih edilir.' },
      { id: 'dome', name: 'Standart dome', text: 'RIC için hazır uç: açık, kapalı veya çift katlı (power).' },
    ],
    careTitle: 'Bakım ipuçları',
    care: [
      'Üreticinin talimatına göre kuru, yumuşak bezle temizleyin; alıcı veya elektronik içeren parçaları suya sokmayın.',
      'Yalnızca elektronik içermeyen hortumlu BTE kalıbını cihazdan ayırıp önerilen yöntemle yıkayın; takmadan önce tamamen kurutun.',
      'Kalıp gevşer ya da ötme sürerse kontrol gerekir; gerekirse yenilenir.',
    ],
    distinction: 'Kulak kalıbı, yüzücü tıkacından ve gürültü koruyucudan farklıdır. Koruyucu tıkaç için de bilgi verebiliriz.',
    cta: 'Kulak kalıbı için randevu',
  },

  process: {
    eyebrow: 'Nasıl ilerliyoruz?',
    h2: 'İlk görüşmeden düzenli takibe dört adım.',
    lead: 'Her adımda ne yaptığımızı ve nedenini anlatırız.',
    steps: [
      { title: 'Görüşme', text: 'Beklentinizi ve günlük ortamlarınızı dinleriz.' },
      { title: 'Değerlendirme', text: 'İşitme testi ve kulak kontrolünden sonra seçenekleri karşılaştırırız.' },
      { title: 'Uygulama', text: 'Cihaz işitmenize göre ayarlanır, kullanımı gösterilir.' },
      { title: 'Takip ve bakım', text: 'İnce ayar randevuları, ardından düzenli kontrol.' },
    ],
    note: 'İşitme cihazı işitmeyi destekler; kaybın nedenine yönelik hekim değerlendirmesinin yerini almaz. Sonuçlar kişiden kişiye değişir.',
  },

  center: {
    eyebrow: 'Merkezimiz',
    h2: 'Keçiören Ayvalı Caddesi\'nde, ulaşımı kolay bir merkez.',
    lead: 'Ferah bekleme alanı ve ayrı görüşme odasıyla, işitme değerlendirmesinden cihaz ayarına kadar tüm süreç aynı merkezde tamamlanır.',
    facts: [
      { label: 'Adres', value: b.address.line },
      { label: 'Telefon', value: b.phone.display },
      ...(canShow(b.hours) ? [{ label: 'Çalışma saatleri', value: 'Pazartesi–Cumartesi 09:00–\u206019:00' }] : []),
    ],
    teamTitle: 'Uzman ekibimiz',
    teamText: 'Sizi dinleyerek başlıyor, ihtiyaçlarınızı ve günlük yaşamınızı birlikte değerlendiriyoruz. Cihaz seçiminden kişiye özel uygulamaya, alışma sürecinden bakım ve düzenli takibe kadar her adımda size eşlik ediyoruz. Sorularınızı yanıtlamak ve cihazınızı günlük hayatınızda rahatça kullanabilmeniz için yanınızdayız.',
    galleryLabel: 'Merkez fotoğrafları',
    photos: [
      { key: 'ofis-6', alt: 'Ayaz İşitme Cihazları mağaza cephesi, Ayvalı Caddesi, Keçiören', caption: 'Ayvalı Caddesi üzerindeki merkezimiz' },
      { key: 'ofis-1', alt: 'Ayaz İşitme Merkezi görüşme odası ve ekip üyesi', caption: 'Görüşme ve uygulama odası' },
      { key: 'ofis-3', alt: 'Bekleme alanı: koltuklar, bitkiler ve cadde manzaralı vitrin', caption: 'Bekleme alanı' },
      { key: 'ofis-5', alt: 'Görüşme odası: uzman masası, pil standı ve duvarda işitme anatomisi posteri', caption: 'Görüşme odası' },
      { key: 'ofis-7', alt: 'Bekleme alanının girişten görünümü', caption: 'Giriş ve bekleme alanı' },
      { key: 'ofis-8', alt: 'Görüşme odasının kapıdan görünümü', caption: 'Görüşme odasına kapıdan bakış' },
    ],
    directionsCta: 'Yol tarifi al',
  },

  reviews: {
    eyebrow: 'Google yorumları',
    h2: 'Kullanıcılarımız ne diyor?',
    lead: 'Google işletme profilimizdeki deneyimleri okuyabilir, kendi deneyiminizi paylaşabilirsiniz.',
    ratingLabel: 'Google puanı',
    countLabel: (n) => `${n} yorum`,
    seeAll: 'Tüm yorumları Google\'da gör',
    write: 'Yorum yaz',
    attribution: 'Yorumlar Google tarafından sağlanır.',
    loading: 'Yorumlar yükleniyor…',
    offline: 'Yorumlarımız Google\'da',
    offlineText: 'Google işletme profilimizdeki güncel puan ve yorumları görmek için bağlantıyı kullanın.',
    apiNote: 'Google işletme profilimizdeki yorumlardan bir seçki; Google\'ın sunduğu bazı güncel yorumlar da canlı eklenir. Tüm yorumları Google Haritalar\'da okuyabilirsiniz.',
    selectionNote: 'Google işletme profilimizdeki yorumlardan bir seçki. Tüm yorumları Google Haritalar\'da okuyabilirsiniz.',
    carousel: { label: 'Kullanıcı yorumları', prev: 'Önceki yorumlar', next: 'Sonraki yorumlar', pause: 'Otomatik kaydırmayı durdur', play: 'Otomatik kaydırmayı başlat', slide: 'Yorum', googleBadge: 'Google yorumu' },
    linkMode: {
      eyebrow: 'Google işletme profili',
      h2: 'Deneyimler Google\'da',
      lead: 'Merkezimizle ilgili kullanıcı değerlendirmelerini Google işletme profilimizde okuyabilir, kendi deneyiminizi orada paylaşabilirsiniz.',
      seeAll: 'Google\'da değerlendirmeleri gör',
      write: 'Bizi Google\'da değerlendirin',
      note: 'Değerlendirmeler Google\'da, kullanıcıların kendi hesaplarıyla yayımlanır; sitemizde alıntılanmaz.',
    },
  },

  faq: {
    eyebrow: 'Sık sorulan sorular',
    h2: 'Merak edilenler',
    lead: 'Aklınızdaki soru burada yoksa telefon veya WhatsApp ile bize yazın; ekibimiz yardımcı olsun.',
    items: [
      { q: 'İşitme cihazı seçimi nasıl yapılır?', a: 'Önce işitme testi ve kulak kontrolü yapılır. Kaybın derecesi ve türü, kulak kanalı yapısı, el becerisi, gözlük/maske kullanımı ve günlük ortamlarınız (kalabalık, telefon, TV) birlikte değerlendirilir. Buna göre uygun cihaz türleri ve teknoloji seviyeleri karşılaştırılır; cihazı deneyerek karar verirsiniz.' },
      { q: 'Kulak içi mi, kulak arkası mı daha iyi?', a: 'Tek bir "en iyi" yoktur. Kulak arkası ve alıcısı kanalda modeller daha geniş güç aralığı, daha uzun pil ömrü ve daha kolay kullanım sunar. Küçük kulak içi modeller (ITC, CIC, IIC) görünürlük açısından avantajlıdır ancak kulak kiri ve neme daha açıktır. Karar, kayıp derecesi ve kulak yapınıza göre verilir.' },
      { q: 'Şarjlı mı, pilli mi tercih etmeliyim?', a: 'Şarjlı modeller gece şarj ünitesine bırakılır; küçük pilleri tutmakta zorlananlar için pratiktir. Pilli modellerde ise pil değiştirerek kesintisiz kullanım mümkündür ve şarj ünitesine bağımlılık yoktur. Yaşam tarzınıza göre birlikte karar veririz.' },
      { q: 'Cihaz telefonuma bağlanır mı?', a: 'Günümüz modellerinin çoğu Bluetooth ile telefon görüşmesi, müzik ve video sesini doğrudan aktarır. Ancak uyumluluk telefonun modeline, işletim sistemine ve cihazın bağlantı standardına göre değişir; görüşmede telefonunuzla uyum kontrolü yapıyoruz.' },
      { q: 'Kulak kalıbı neden gerekli, nasıl alınır?', a: 'Doğru oturan kalıp cihazı kulakta sabit tutar, sesi kaçırmadan iletir ve ötmeyi azaltır. Önce kulak kanalı otoskopla incelenir; kanala küçük bir koruyucu yerleştirilip silikon ölçü malzemesi uygulanır, birkaç dakikada sertleşir ve ardından kanal yeniden kontrol edilir. İşlem uzman tarafından uygulanır; kalıp kulak yapınıza özel üretilir ve teslimde uyumu kontrol edilir.' },
      { q: 'İlk kullanımda alışma süreci nasıl olur?', a: 'Beyin, uzun süredir duymadığı sesleri yeniden öğrenir. İlk günlerde kendi sesiniz ve ortam sesleri farklı gelebilir. Kademeli kullanım süresi ve ilk haftalardaki ince ayar randevularıyla çoğu kullanıcı birkaç hafta içinde belirgin şekilde alışır.' },
      { q: 'Bakım nasıl yapılır, filtre ne sıklıkla değişir?', a: 'Temizleme, kurutma ve saklamada cihazınızın kullanım kılavuzunu izleyin. Filtre ve dome değişim sıklığı modele ve kulak kiri birikimine göre değişir; önerilen süreyi ve değişim yöntemini uygulamalı gösteriyoruz.' },
      { q: 'İlk randevuda neler yapılır, ne getirmeliyim?', a: `Görüşme, kulak kontrolü ve işitme testi yapılır; sonuçlar açıklanır ve seçenekler anlatılır. ${canShow(b.claims.sgkContracted) ? 'Varsa önceki işitme testi sonuçlarınızı, kullandığınız cihazı ve SGK süreci için kimliğinizi getirmeniz yeterlidir.' : 'Varsa önceki işitme testi sonuçlarınızı ve kullandığınız cihazı getirmeniz yeterlidir.'}` },
      { q: 'İşitme cihazı fiyatını ne belirler?', a: 'Fiyat; cihazın türünden çok teknoloji seviyesine (gürültü işleme, bağlantı, şarj), kanal sayısına ve ek hizmetlere göre değişir. Değerlendirme sonrası ihtiyacınıza uygun farklı seviyelerde net fiyat bilgisi veriyoruz.' },
      ...(canShow(b.claims.sgkContracted)
        ? [{ q: 'SGK işitme cihazı için ne kadar ödüyor, süreç nasıl işler?', a: 'SGK, sağlık kurulu raporu ve reçete şartıyla belirli tutarda katkı sağlar; tutarlar ve koşullar Sağlık Uygulama Tebliği ile güncellenir. SGK anlaşmalı merkez olarak belge sürecinde yol gösteriyor, güncel koşulları görüşmede paylaşıyoruz.' }]
        : []),
    ],
  },

  contact: {
    eyebrow: 'İletişim ve randevu',
    h2: 'Bir görüşme için bize ulaşın.',
    lead: 'Telefon veya WhatsApp ile hemen; ya da kısa formu bırakın, sizi arayalım. Randevu talebi, ekibimiz sizi arayıp saat teyit ettiğinde kesinleşir.',
    form: {
      title: 'Randevu talebi',
      name: 'Ad Soyad',
      phone: 'Telefon',
      time: 'Sizi ne zaman arayalım?',
      timeOptions: ['Fark etmez', 'Sabah (09:00–12:00)', 'Öğleden sonra (12:00–15:00)', 'Akşamüstü (15:00–19:00)'],
      note: 'Sağlık bilgisi, rapor veya odyogram istemiyoruz; bunları görüşmede birlikte değerlendiririz.',
      consent: 'Randevu için iletişim bilgilerimin işlenmesine ilişkin aydınlatma metnini okudum.',
      consentLink: 'Aydınlatma metni',
      submit: 'Randevu Talebi Gönder',
      submitWhatsapp: 'WhatsApp ile Gönder',
      sending: 'Gönderiliyor…',
      successTitle: 'Talebiniz alındı',
      successText: 'Ekibimiz uygun bir randevu saati belirlemek için sizinle iletişime geçecek. Tercih ettiğiniz saat aralığını dikkate alacağız.',
      errorTitle: 'Gönderilemedi',
      errorText: 'Bir sorun oluştu. Lütfen telefon veya WhatsApp ile ulaşın.',
      fallbackNotice: 'Form, talebinizi hazır bir WhatsApp mesajına dönüştürür; göndermek için WhatsApp\'ta onaylamanız yeterlidir.',
      noScript: 'Formu kullanmak için tarayıcınızda JavaScript açık olmalıdır. Bize telefon veya WhatsApp ile de ulaşabilirsiniz.',
      requiredNote: 'Zorunlu alanlar',
      validation: {
        name: 'Lütfen adınızı ve soyadınızı yazın.',
        phone: 'Lütfen geçerli bir telefon numarası yazın (ör. 05xx xxx xx xx).',
        consent: 'Devam etmek için aydınlatma metnini onaylayın.',
        time: 'Lütfen bir zaman aralığı seçin.',
      },
    },
    info: {
      address: 'Adres',
      phone: 'Telefon',
      whatsapp: 'WhatsApp',
      email: 'E-posta',
      hours: 'Çalışma saatleri',
      hoursValue: 'Pazartesi–Cumartesi 09:00–\u206019:00',
      closed: 'Pazar kapalı',
      directions: 'Yol tarifi',
      loadMap: 'Haritayı yükle',
      mapNote: 'Harita Google tarafından sağlanır ve izin beklemeden yüklenir; IP adresiniz ve sayfa adresi Google\'a iletilir, Google çerez kullanabilir. Adres ve telefon bu bölümde metin olarak da yer alır.',
    },
  },

  footer: {
    legal: b.legalName,
    privacy: 'Gizlilik ve KVKK',
    cookies: 'Çerez tercihleri',
    rights: 'Tüm hakları saklıdır.',
    quick: 'Hızlı erişim',
    contact: 'İletişim',
    disclaimer: 'Bu sitedeki bilgiler genel bilgilendirme amaçlıdır; tıbbi tanı veya tedavi yerine geçmez. Marka adları ilgili şirketlerin tescilli markalarıdır.',
  },

  consent: {
    title: 'Çerez tercihleri',
    noticeTitle: 'Çerezler hakkında',
    textWithOptional: 'Sitemizin kendi kodu çerez kullanmaz. İsteğe bağlı ölçüm hizmetleri ({services}) yalnızca izin verirseniz yüklenir. İletişim bölümündeki Google Haritalar haritası ise izin beklemeden yüklenir; ayrıntılar çerez politikasında.',
    textNoticeOnly: 'Sitemizin kendi kodu çerez kullanmaz ve bu sitede analitik veya reklam ölçüm hizmeti çalışmaz. İletişim bölümündeki Google Haritalar haritası izin beklemeden yüklenir; Google çerez kullanabilir. Ayrıntılar çerez politikasında.',
    and: 've',
    acceptAll: 'Tümünü kabul et',
    rejectAll: 'Yalnızca zorunlu',
    manage: 'Tercihleri yönet',
    save: 'Seçimi kaydet',
    acknowledge: 'Anladım',
    categories: {
      necessary: { label: 'Zorunlu', text: 'Sitenin çalışması ve tercihlerinizin hatırlanması için gerekli. Kapatılamaz.' },
      analytics: { label: 'Analitik', text: 'Sayfanın nasıl kullanıldığını anlamamızı sağlar ({services}). Kullanım ve cihaz bilgileri işlenebilir; formdaki adınız ve telefonunuz analitiğe gönderilmez.' },
      marketing: { label: 'Pazarlama', text: 'Reklam kampanyalarının etkisini ölçmek için kullanılır ({services}). Yalnızca izninizle çalışır.' },
    },
    reopen: 'Çerez tercihleri',
    policyLink: 'Çerez politikası',
  },

  mobileBar: { call: 'Ara', whatsapp: 'WhatsApp', directions: 'Yol tarifi' },

  common: {
    skip: 'İçeriğe geç',
    menu: 'Menü',
    close: 'Kapat',
    back: 'Geri',
    next: 'Sonraki',
    prev: 'Önceki',
    learnMore: 'Bilgi al',
    new: 'Yeni',
  },
};
